## I will explore the data to determine how to split it

In [162]:
import pandas as pd

In [163]:
Customers_df=pd.read_csv("Raw_data/olist_customers_dataset.csv")

In [164]:
Customers_df

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP
...,...,...,...,...,...
99436,17ddf5dd5d51696bb3d7c6291687be6f,1a29b476fee25c95fbafc67c5ac95cf8,3937,sao paulo,SP
99437,e7b71a9017aa05c9a7fd292d714858e8,d52a67c98be1cf6a5c84435bd38d095d,6764,taboao da serra,SP
99438,5e28dfe12db7fb50a4b2f691faecea5e,e9f50caf99f032f0bf3c55141f019d99,60115,fortaleza,CE
99439,56b18e2166679b8a959d72dd06da27f9,73c2643a0a458b49f58cea58833b192e,92120,canoas,RS
99440,274fa6071e5e17fe303b9748641082c8,84732c5050c01db9b23e19ba39899398,6703,cotia,SP

In [165]:
geolocation_df=pd.read_csv("Raw_data/olist_geolocation_dataset.csv")
geolocation_df

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP
...,...,...,...,...,...
1000158,99950,-28.068639,-52.010705,tapejara,RS
1000159,99900,-27.877125,-52.224882,getulio vargas,RS
1000160,99950,-28.071855,-52.014716,tapejara,RS
1000161,99980,-28.388932,-51.846871,david canabarro,RS
1000162,99950,-28.070104,-52.018658,tapejara,RS

In [166]:
Order_Items_df=pd.read_csv("Raw_data/olist_order_items_dataset.csv")

In [167]:
Order_Items_df

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14
...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79

In [168]:
Order_Payments_df=pd.read_csv("Raw_data/olist_order_payments_dataset.csv")

In [169]:
Order_Payments_df

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45
...,...,...,...,...,...
103881,0406037ad97740d563a178ecc7a2075c,1,boleto,1,363.31
103882,7b905861d7c825891d6347454ea7863f,1,credit_card,2,96.80
103883,32609bbb3dd69b3c066a6860554a77bf,1,credit_card,1,47.77
103884,b8b61059626efa996a60be9bb9320e10,1,credit_card,5,369.54
103885,28bbae6599b09d39ca406b747b6632b1,1,boleto,1,191.58

In [170]:
Order_Reviews_df=pd.read_csv("Raw_data/olist_order_reviews_dataset.csv")

In [171]:
Order_Reviews_df

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53
...,...,...,...,...,...,...,...
99219,574ed12dd733e5fa530cfd4bbf39d7c9,2a8c23fee101d4d5662fa670396eb8da,5,NaN,NaN,2018-07-07 00:00:00,2018-07-14 17:18:30
99220,f3897127253a9592a73be9bdfdf4ed7a,22ec9f0669f784db00fa86d035cf8602,5,NaN,NaN,2017-12-09 00:00:00,2017-12-11 20:06:42
99221,b3de70c89b1510c4cd3d0649fd302472,55d4004744368f5571d1f590031933e4,5,NaN,"Excelente mochila, entrega super rápida. Super...",2018-03-22 00:00:00,2018-03-23 09:10:43
99222,1adeb9d84d72fe4e337617733eb85149,7725825d039fc1f0ceb7635e3f7d9206,4,NaN,NaN,2018-07-01 00:00:00,2018-07-02 12:59:13
99223,efe49f1d6f951dd88b51e6ccd4cc548f,90531360ecb1eec2a1fbb265a0db0508,1,NaN,"meu produto chegou e ja tenho que devolver, po...",2017-07-03 00:00:00,2017-07-03 21:01:49

In [172]:
Orders_df=pd.read_csv("Raw_data/olist_orders_dataset.csv")

In [173]:
Orders_df

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00
...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28 00:00:00
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00

In [174]:
Products_df=pd.read_csv("Raw_data/olist_products_dataset.csv")

In [175]:
Products_df

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0
...,...,...,...,...,...,...,...,...,...
32946,a0b7d5a992ccda646f2d34e418fff5a0,moveis_decoracao,45.0,67.0,2.0,12300.0,40.0,40.0,40.0
32947,bf4538d88321d0fd4412a93c974510e6,construcao_ferramentas_iluminacao,41.0,971.0,1.0,1700.0,16.0,19.0,16.0
32948,9a7c6041fa9592d9d9ef6cfe62a71f8c,cama_mesa_banho,50.0,799.0,1.0,1400.0,27.0,7.0,27.0
32949,83808703fc0706a22e264b9d75f04a2e,informatica_acessorios,60.0,156.0,2.0,700.0,31.0,13.0,20.0
32950,106392145fca363410d287a815be6de4,cama_mesa_banho,58.0,309.0,1.0,2083.0,12.0,2.0,7.0

## The Category Name in Portuguese so we need to make it English

In [176]:
Sellers_df=pd.read_csv("Raw_data/olist_sellers_dataset.csv")

In [177]:
Sellers_df

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP
...,...,...,...,...
3090,98dddbc4601dd4443ca174359b237166,87111,sarandi,PR
3091,f8201cab383e484733266d1906e2fdfa,88137,palhoca,SC
3092,74871d19219c7d518d0090283e03c137,4650,sao paulo,SP
3093,e603cf3fec55f8697c9059638d6c8eb5,96080,pelotas,RS
3094,9e25199f6ef7e7c347120ff175652c3b,12051,taubate,SP

In [178]:
Translation_df=pd.read_csv("Raw_data/product_category_name_translation.csv")

In [179]:
Translation_df

            product_category_name product_category_name_english
0                    beleza_saude                 health_beauty
1          informatica_acessorios         computers_accessories
2                      automotivo                          auto
3                 cama_mesa_banho                bed_bath_table
4                moveis_decoracao               furniture_decor
..                            ...                           ...
66                         flores                       flowers
67             artes_e_artesanato         arts_and_craftmanship
68                fraldas_higiene           diapers_and_hygiene
69  fashion_roupa_infanto_juvenil     fashion_childrens_clothes
70             seguros_e_servicos         security_and_services

[71 rows x 2 columns]

## I will split tables baesd on quarters

In [180]:
Orders_df

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00
...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28 00:00:00
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00

In [181]:
Orders_df["order_purchase_timestamp"] = pd.to_datetime(Orders_df["order_purchase_timestamp"])
Orders_df["year"] = Orders_df["order_purchase_timestamp"].dt.year
Orders_df["quarter"] = Orders_df["order_purchase_timestamp"].dt.quarter
Orders_df

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,year,quarter
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,2017,4
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,2018,3
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,2018,3
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00,2017,4
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00,2018,1
...,...,...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28 00:00:00,2017,1
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00,2018,1
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00,2017,3
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00,2018,1
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00,2018,1

In [182]:
Orders_Q3_2016=Orders_df[(Orders_df["year"]==2016) & (Orders_df["quarter"]==3)]

In [183]:
Customers_ids=Orders_Q3_2016["customer_id"]
Customers_ids

4396     683c54fc24d40ee9f8a6fc179fd9856c
4541     08c5351a6aca1c1589a38f244edeee9d
10071    622e13439d6b5a0b486c435618b2679e
30710    86dc2ffce2dfff336de2f386a786e574
Name: customer_id, dtype: object

In [184]:
Customers_Q3_2016=Customers_df[Customers_df["customer_id"].isin(Customers_ids)]
Customers_Q3_2016

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
21125,86dc2ffce2dfff336de2f386a786e574,830d5b7aaa3b6f1e9ad63703bec97d23,14600,sao joaquim da barra,SP
70561,683c54fc24d40ee9f8a6fc179fd9856c,4854e9b3feff728c13ee5fc7d1547e92,99025,passo fundo,RS
84697,08c5351a6aca1c1589a38f244edeee9d,b7d76e111c89f7ebf14761390f0f7d17,69309,boa vista,RR
84845,622e13439d6b5a0b486c435618b2679e,009b0127b727ab0ba422f6d9604487c7,12244,sao jose dos campos,SP

In [185]:
Orders_ids=Orders_Q3_2016["order_id"]
Orders_ids

4396     e5fa5a7210941f7d56d0208e4e071d35
4541     2e7a8482f6fb09756ca50c10d7bfc047
10071    809a282bbd5dbcabb6f2f724fca862ec
30710    bfbd0f9bdef84302105ad712db648a6c
Name: order_id, dtype: object

In [186]:
Order_items_Q3_2016=Order_Items_df[Order_Items_df["order_id"].isin(Orders_ids)]
Order_items_Q3_2016

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
20265,2e7a8482f6fb09756ca50c10d7bfc047,1,c1488892604e4ba5cff5b4eb4d595400,1554a68530182680ad5c8b042c3ab563,2016-10-26 18:25:19,39.99,31.67
20266,2e7a8482f6fb09756ca50c10d7bfc047,2,f293394c72c9b5fafd7023301fc21fc2,1554a68530182680ad5c8b042c3ab563,2016-10-26 18:25:19,32.90,31.67
84389,bfbd0f9bdef84302105ad712db648a6c,1,5a6b04657a4c5ee34285d1e4619a96b4,ecccfa2bb93b34a3bf033cc5d1dcdc69,2016-09-19 23:11:33,44.99,2.83
84390,bfbd0f9bdef84302105ad712db648a6c,2,5a6b04657a4c5ee34285d1e4619a96b4,ecccfa2bb93b34a3bf033cc5d1dcdc69,2016-09-19 23:11:33,44.99,2.83
84391,bfbd0f9bdef84302105ad712db648a6c,3,5a6b04657a4c5ee34285d1e4619a96b4,ecccfa2bb93b34a3bf033cc5d1dcdc69,2016-09-19 23:11:33,44.99,2.83
101394,e5fa5a7210941f7d56d0208e4e071d35,1,f3c2d01a84c947b078e32bbef0718962,a425f92c199eb576938df686728acd20,2016-09-19 00:15:34,59.50,15.56

In [187]:
Order_Payments_Q3_2016=Order_Payments_df[Order_Payments_df["order_id"].isin(Orders_ids)]
Order_Payments_Q3_2016

,order_id,payment_sequential,payment_type,payment_installments,payment_value
27216,2e7a8482f6fb09756ca50c10d7bfc047,1,credit_card,1,136.23
58826,809a282bbd5dbcabb6f2f724fca862ec,1,credit_card,2,40.95
61536,e5fa5a7210941f7d56d0208e4e071d35,1,credit_card,3,75.06

In [188]:
Order_reviews_Q3_2016=Order_Reviews_df[Order_Reviews_df["order_id"].isin(Orders_ids)]
Order_reviews_Q3_2016

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
30479,a93139d9d1314158c080e3db7e79618b,e5fa5a7210941f7d56d0208e4e071d35,1,NaN,Comprei dois produtos desta loja parceira da l...,2016-10-29 00:00:00,2016-10-30 01:47:48
37547,6916ca4502d6d3bfd39818759d55d536,bfbd0f9bdef84302105ad712db648a6c,1,NaN,nao recebi o produto e nem resposta da empresa,2016-10-06 00:00:00,2016-10-07 18:32:28
70906,69ac6a27fde9855ebeaaecac0f78058b,809a282bbd5dbcabb6f2f724fca862ec,1,NaN,MEU PEDIDO NÃO FOI ENTREGUE E NÃO FOI DADA NEN...,2016-10-02 00:00:00,2016-10-26 12:31:00
74443,cef1ee03ded4d6272894a2eead6e1328,2e7a8482f6fb09756ca50c10d7bfc047,1,NaN,1 mes de atraso na entrega !!! ultima compra q...,2016-10-22 00:00:00,2016-11-15 16:00:34

In [189]:
import os 
os.makedirs("New_Raw_Data", exist_ok=True)

In [190]:
os.makedirs("New_Raw_Data/Orders_Q3_2016", exist_ok=True)
Orders_Q3_2016.to_csv("New_Raw_Data/Orders_Q3_2016/Orders_Q3_2016.csv")

In [191]:
Customers_Q3_2016.to_csv("New_Raw_Data/Orders_Q3_2016/Customers_Q3_2016.csv")

In [192]:
Order_items_Q3_2016.to_csv("New_Raw_Data/Orders_Q3_2016/order_items_Q3_2016.csv")

In [193]:
Order_Payments_Q3_2016.to_csv("New_Raw_Data/Orders_Q3_2016/Order_Payments_Q3_2016.csv")

In [194]:
Order_reviews_Q3_2016.to_csv("New_Raw_Data/Orders_Q3_2016/order_reviews_Q3_2016.csv")

In [195]:
Orders_Q4_2016=Orders_df[(Orders_df["year"]==2016) & (Orders_df["quarter"]==4)]

In [196]:
Customers_ids=Orders_Q4_2016["customer_id"]
Customers_ids

324      957f8e082185574de25992dc659ebbc0
378      dacb079d55ffb1d3955c5d923df3ebb7
699      ef21aebbb093a6db29ccc6aa0b89c347
1384     7f0ca17bb33b230b47459437cf0682c7
1449     ff1a56726b7ea149c7423865609cc0c8
                       ...
98322    1fc56719b52f82c03caddc5faf531fbb
98484    0a9ee4d9030acbe428769c79d0c4da69
99035    accfbaa1f092fdf6db1d8fcdad351b50
99248    e9c6723e04c4e53e7e9c3afe383f3866
99292    efc07f50d0a9346ec00e1c37b5b10748
Name: customer_id, Length: 325, dtype: object

In [197]:
Customers_Q4_2016=Customers_df[Customers_df["customer_id"].isin(Customers_ids)]
Customers_Q4_2016

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
347,77069f163bef4933c6efeea244b3f606,99e41e69b60bd63edd83935499523063,21616,rio de janeiro,RJ
386,17e6d37366dc8c8865588b0d1740d606,3c34090736785a45dd8cbf536ad289c4,86181,cambe,PR
748,1013b3cb87e89aa951b7f556f8c26d33,0032c76b20340da25249092a268ce66c,13515,charqueada,SP
920,edf0b9f3196ff6f4702be2d540f684d4,171d92af5bf025428dfc2fd869eb8a04,21715,rio de janeiro,RJ
1883,5bef68c4d2d04c09aee2195ff540f131,d8e40a4b16990a6fd1095feae46aa1af,13562,sao carlos,SP
...,...,...,...,...,...
98428,0c63b4438ff050942153aaa4c19ad1d3,8ca747eb93e7b8d6a56532b8f074d185,38414,uberlandia,MG
98555,6fa16a8d44a2d9a89710e9758688c7f2,840048bff3cbd6d92d97a3816521222e,4841,sao paulo,SP
98927,a25c191eb1025845e8e9d1d806fa2605,a311db8053cf14527828dd6d89a1f57a,98801,santo angelo,RS
98934,a0f95ab56c6d3a5ba0036b7fdfeda07f,a9530b74fe56ca4be9e5f2c7e7c4175a,89124,benedito novo,SC
99176,da231380834f900e3fc3a958a1533a33,e3626c985901df173504f3d285ac823f,24937,marica,RJ

In [198]:
Orders_ids=Orders_Q4_2016["order_id"]
Orders_ids

324      d3c8851a6651eeff2f73b0e011ac45d0
378      cbbb524a0e1646aa6cf7a3c0bbe517ad
699      ac2b7c522d811acba0aa270ed3e112e4
1384     7033745709b7cf1bac7d2533663592de
1449     5cd498954e2b37d71b315166809b4bd7
                       ...
98322    6e0d2539e48e84296bae6290de41058c
98484    9d664ec86be69d869bb6870294c4fdd8
99035    7e2dddf174cc4d2768bf39c43ab2bd7a
99248    e439ced3d48f1a77f6ecc029cc946a6f
99292    509a52223ecac6d67fb765b3b37c6974
Name: order_id, Length: 325, dtype: object

In [199]:
Order_items_Q4_2016=Order_Items_df[Order_Items_df["order_id"].isin(Orders_ids)]
Order_items_Q4_2016

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
908,02190241f7190a1f3c7e0df95a749c6a,1,e00d2c49504aeaf7acdc9ff7cf8a6107,46dc3b2cc0980fb8ec44634e21d2718e,2016-10-12 04:44:23,249.99,10.74
909,02190241f7190a1f3c7e0df95a749c6a,2,e00d2c49504aeaf7acdc9ff7cf8a6107,46dc3b2cc0980fb8ec44634e21d2718e,2016-10-12 04:44:23,249.99,10.74
911,021d08e4057e5b6414c8d2f69f4f72a0,1,a819714dd23a6ac18b1be2b13686017b,ffff564a4f9085cd26170f4732393726,2016-10-17 19:01:41,51.50,14.53
1138,02a0eb7c22b0616c767a45954a2a28f6,1,5f8c74f4a3d2b616857fcb7d4dd1f61a,83e197e95a1bbabc8c75e883ed016c47,2016-10-14 08:14:53,119.50,25.04
1320,03128233e78ed8ade6738f2043f4cf8d,1,3cacd5299c846cb08ae1e445fd78392b,c7dcd301ecfe5ab7f778ac172cf74be7,2016-10-21 16:25:24,57.90,14.61
...,...,...,...,...,...,...,...
109873,f9b03f7a6e5788ffb6cb6b4cd0d01892,1,44377a26f7c80dbf0a9b2b300604e6bf,ecccfa2bb93b34a3bf033cc5d1dcdc69,2016-10-15 05:02:52,99.90,16.27
109906,f9c44da06151c190a9a6c9c712873d10,1,b864b103180d5a6a3f830e67f93e8735,f5b84683a9bf9e1df748cf40f601b39c,2016-10-15 15:09:06,83.90,9.07
110607,fb5114c39f632a52598cf770c6076620,1,269e87010f6d5e57015a90b00983e334,0db783cfcd3b73998abc6e10e59a102f,2016-10-13 14:35:36,35.00,16.05
110800,fbbc9a4fa88f1ccd651790df665b3e57,1,44377a26f7c80dbf0a9b2b300604e6bf,ecccfa2bb93b34a3bf033cc5d1dcdc69,2016-10-09 02:45:17,99.90,19.53
111500,fd4b04818375a4ba579a80c8d37f1b24,1,34239894e175b17d8c84edc6c73b4dad,827f8f69dfa529c561901c4f2e0f332f,2016-10-11 14:31:44,27.90,14.52

In [200]:
Order_Payments_Q4_2016=Order_Payments_df[Order_Payments_df["order_id"].isin(Orders_ids)]
Order_Payments_Q4_2016

,order_id,payment_sequential,payment_type,payment_installments,payment_value
155,3b697a20d9e427646d92567910af6d57,1,boleto,1,45.46
332,c776863a93dc0740c6e7d78104b21413,1,credit_card,3,264.08
368,ed90ba41c41da31da8e891ff43a584d1,1,credit_card,7,156.22
1236,d3f7c0e804b501782903f7af749eb797,1,credit_card,10,784.80
1377,c8258090bca7cc6a62c1e15d7fd995d4,1,credit_card,2,150.99
...,...,...,...,...,...
101843,1b2d622f7ebb8e65f7de3e389f052540,1,credit_card,4,51.93
102434,d01f0aba52a4d7b2cca8d7623538a434,1,credit_card,3,75.84
102788,45ec58d30f2023e4dac16d956a657ddd,1,boleto,1,87.51
103022,e2eaf909eb6ba881117aa407992a5ffb,1,boleto,1,115.22
103061,cda873529ca7ab71f677d5ec11a40304,1,credit_card,2,75.90

In [201]:
Order_reviews_Q4_2016=Order_Reviews_df[Order_Reviews_df["order_id"].isin(Orders_ids)]
Order_reviews_Q4_2016

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
68,6d06808638ec0701bccd70bc8d462c28,97d2f8fe76f2f253b8291e17b5383884,1,NaN,O produto não chegou no prazo estipulado e cau...,2016-12-09 00:00:00,2016-12-19 14:10:43
133,2685a4800004a12ec09d27264ff1915f,5c973d2b4652e1dec15353b59339f3b4,5,NaN,Recomendo a todos os clientes,2016-10-22 00:00:00,2016-10-26 17:47:19
198,d36219dfadc3a5b07ab66670d23915ad,22613579f7d11cc59c4347526fc3c79e,5,NaN,Acho que rastreando o produto devia ser melhor...,2016-10-19 00:00:00,2016-10-20 12:40:59
239,a36150969fe6bd09ed011dd78aeb0189,ef1b29b591d31d57c0d7337460dd83c9,1,NaN,"Demora na entrega, detestei o atendimento e NU...",2016-11-02 00:00:00,2016-11-03 12:04:24
641,2f17f8ffe35062ac9d76c4dde9c181eb,06d7e8a85f5cfef576c5303ed7d7f2e5,4,NaN,Entrega feita no prazo e produto em perfeitas ...,2016-10-20 00:00:00,2016-10-20 21:56:45
...,...,...,...,...,...,...,...
97862,984ab9fb9c9785407beb46bc068974e2,2825848807f070485f0f0ef3829758f4,5,NaN,"Entrega antes do prazo, adorei meu produto,per...",2016-10-19 00:00:00,2016-10-20 01:46:12
98067,b8b1e3d3475e57893affe9798daad68d,d743f434cc2921729af830ce00d474b3,3,NaN,É bem bonita e bem acabada mais pena q veio a ...,2016-10-25 00:00:00,2016-10-28 00:50:19
98370,dc62f1e20d7f280e54066b6a92841086,be5bc2f0da14d8071e2d45451ad119d9,4,NaN,Tudo certo...,2016-10-28 00:00:00,2016-10-29 11:29:53
99041,e1bc9e2f33c3fa1cb40845c285f0c02b,dd359d3c294458c6d642b2eea9212bf5,2,NaN,"Já comprei várias vezes no site ""lannister"";ma...",2016-11-27 00:00:00,2016-11-29 14:19:59
99078,2ba0e39ea1f450e280e1dd700eb248e3,3f72d2b757e725cd48a4726f831c7789,3,NaN,NaN,2016-10-26 00:00:00,2016-10-27 23:05:25

In [202]:
os.makedirs("New_Raw_Data/Orders_Q4_2016", exist_ok=True)
Orders_Q4_2016.to_csv("New_Raw_Data/Orders_Q4_2016/Orders_Q4_2016.csv")

In [203]:
Customers_Q4_2016.to_csv("New_Raw_Data/Orders_Q4_2016/Customers_Q4_2016.csv")

In [204]:
Order_items_Q4_2016.to_csv("New_Raw_Data/Orders_Q4_2016/order_items_Q4_2016.csv")

In [205]:
Order_Payments_Q4_2016.to_csv("New_Raw_Data/Orders_Q4_2016/Order_Payments_Q4_2016.csv")

In [206]:
Order_reviews_Q4_2016.to_csv("New_Raw_Data/Orders_Q4_2016/order_reviews_Q4_2016.csv")

In [207]:
Orders_Q1_2017=Orders_df[(Orders_df["year"]==2017) & (Orders_df["quarter"]==1)]

In [208]:
Customers_ids=Orders_Q1_2017["customer_id"]
Customers_ids

8        f54a9f0e6b351c431402b8461ea51999
58       911e4c37f5cafe1604fe6767034bf1ae
73       a90391a47de936d56c66a5366cba1462
98       0bf19317b1830a69e55b40710576aa7a
106      48f239e15744ed5e7ffbafc6bb6e882b
                       ...
99329    3fb83e207757e8f15ff70d937c86929b
99368    a14f464b2a19d761f7f3f0885d5ea955
99434    f01a6bfcc730456317e4081fe0c9940e
99435    47cd45a6ac7b9fb16537df2ccffeb5ac
99436    39bd1228ee8140590ac3aca26f2dfe00
Name: customer_id, Length: 5262, dtype: object

In [209]:
Customers_Q1_2017=Customers_df[Customers_df["customer_id"].isin(Customers_ids)]
Customers_Q1_2017

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
49,4d27341acd30a36bca39008ee9bb9050,e021e698833bdeb89dfef3acb2e91f37,89254,jaragua do sul,SC
75,0aae2862f8eac77f10a34f44860720ac,cd076285a12f40041b32f5ad8c98699f,5890,sao paulo,SP
82,38d1cd89306128348ffdf4cc23f3a50a,d491a65a6ef3c04e145d37395996bad7,4548,sao paulo,SP
103,126cf4e9fd189d2d64bc9b112fd6a5e8,90d479448b39ad9586d05da64cfb695b,62016,sobral,CE
111,eb67e9bd3357fbacdbef99759f919573,4bc7250d4b42b3374eb6f41b12429592,4710,sao paulo,SP
...,...,...,...,...,...
99407,e98998055b4804137a020830903f93f2,e097d846931763789c3fd00b27f3c325,3057,sao paulo,SP
99411,da37711b17efd5f2539e8196ab215f04,5f2971f9805e3ccb030226e30c8e8390,4313,sao paulo,SP
99420,be631308cb609ff74d0e0fb54815e18c,1c137fe37df712015f6488edafe8ece4,36255,aracitaba,MG
99428,ffa6d90c36a9c7004692ca50761c69d6,874c93d867b18eb09a5e2f071ee89458,13140,paulinia,SP
99433,14308d2303a3e2bdf4939b86c46d2679,e7f8760e2bbd2f1986bebd99596c088e,66033,belem,PA

In [210]:
Orders_ids=Orders_Q1_2017["order_id"]
Orders_ids

8        76c6e866289321a7c93b82b54852dc33
58       a685d016c8a26f71a0bb67821070e398
73       974c1993ab8024d3ed16229183c2308d
98       f7959f8385f34c4f645327465a1c9fc4
106      a6cd683d4bd3b9b1f0aa37b27f8116d3
                       ...
99329    9058bc799c3791077efb3aaa8e0d5e02
99368    dbd4cbb492a12b99c5224014930acc18
99434    aa04ef5214580b06b10e2a378300db44
99435    880675dff2150932f1601e1c07eadeeb
99436    9c5dedf39a927c1b2549525ed64a053c
Name: order_id, Length: 5262, dtype: object

In [211]:
Order_items_Q1_2017=Order_Items_df[Order_Items_df["order_id"].isin(Orders_ids)]
Order_items_Q1_2017

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14
27,00125cb692d04887809806618a2a145f,1,1c0c0093a48f13ba70d0c6b0a9157cb7,41b39e28db005d9731d9d485a83b4c38,2017-03-29 13:05:42,109.90,25.51
51,001dbc16dc51075e987543d23a0507c7,1,777d2e438a1b645f3aec9bd57e92672c,4a3ca9315b744ce9f8e9374361493884,2017-02-01 13:17:57,69.90,18.00
52,001e7ba991be1b19605ca0316e7130f9,1,884fa3cd42986ba480ea2f8ae4e25ff7,3340ef1913fb70d28420f6ceb685c339,2017-03-23 11:47:37,195.00,18.21
63,002691433f09002ac9ca0c4e8dbb8ead,1,430d215740da7fdda91cc938f8fd92f6,0887a9f087bcd5d9f6642b52f897fc6c,2017-02-06 21:18:03,104.00,16.43
...,...,...,...,...,...,...,...
112563,ffcbf9b4459704e9185c5c630d11b69c,1,9ae3dacfd2327107a1e28274fac25a4e,0c8380b62e38e8a1e6adbeba7eb9688c,2017-03-02 08:01:52,109.90,27.24
112572,ffd5efbd46bbf72ad374862a05ef4c72,1,8338cef8355d238f43711dcb9c0657b2,cca3071e3e9bb7d12640c9fbe2301306,2017-02-11 18:39:14,45.90,14.52
112586,ffdc5e3279114c523a09296f8fd28331,1,5e70a4508abd5d19bfe7f110785294c8,328acb143b4a73aad6bee8e734f5d20d,2017-02-14 14:49:23,299.99,17.80
112601,ffe49171e120186dcc4c444b55691810,1,102cdda7fcf3cb71b5f9d6d2a3e56b58,8931a84a914b3fe9b1ddaa4d704947ca,2017-04-04 02:15:36,68.00,8.85
112610,ffea406a848c8afe4dec22bf6290ba00,1,801a695ff5c0c14970a71a4ceb70989e,48162d548f5b1b11b9d29d1e01f75a61,2017-03-21 17:16:36,146.90,15.20

In [212]:
Order_Payments_Q1_2017=Order_Payments_df[Order_Payments_df["order_id"].isin(Orders_ids)]
Order_Payments_Q1_2017

,order_id,payment_sequential,payment_type,payment_installments,payment_value
21,4214cda550ece8ee66441f459dc33a8c,1,credit_card,2,170.57
33,f9d0ec2fa088ac583e1ccd15b6686073,1,credit_card,1,89.68
58,343348b1e29e9fa9e7b6ab1027f9177d,1,credit_card,4,43.77
61,3ab4eea6776259ae8dfbabaeffece352,1,credit_card,8,387.80
70,e3e9e3295f4e1512167c232a0aaae8a5,1,voucher,1,50.80
...,...,...,...,...,...
103741,4fbc2bd17fd14bf9e9b4f28f96351edf,1,voucher,1,27.86
103752,976967517bb3199cd529dd524e39e82a,1,credit_card,2,64.42
103756,1409fa8d66178147ed431573330397c0,1,credit_card,10,441.32
103766,b17fd4c033b06e8d888de8ea6105ef9d,1,credit_card,5,103.10
103862,807f4ef550f104708e2190eca7e4c37a,1,credit_card,3,205.71

In [213]:
Order_reviews_Q1_2017=Order_Reviews_df[Order_Reviews_df["order_id"].isin(Orders_ids)]
Order_reviews_Q1_2017

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
39,9fd59cd04b42f600df9f25e54082a8d1,3c314f50bc654f3c4e317b055681dff9,1,NaN,Nada de chegar o meu pedido.,2017-04-21 00:00:00,2017-04-23 05:37:03
55,3d94fd645cdaacc8c9f0dc0a2a1f5166,4d483bf690ca21bdc005df9b623673c7,5,NaN,boa,2017-03-21 00:00:00,2017-03-22 00:58:49
83,34e5d18f3bb64d586812f8f1d8b53097,bf6861804f97bcf7644f603c5bcf7784,4,NaN,NaN,2017-03-31 00:00:00,2017-04-01 23:43:01
87,0bd4dcc4f6c4621baf37f73495cad8c4,a11cd01ac67beef7e8bf09740d8a35c1,3,NaN,Entrega no prazo,2017-03-23 00:00:00,2017-03-23 21:20:16
152,e2fd85e5df711bd91e6e96e13c741843,c9645496b715730a1a5d07eb97a6bf6b,5,NaN,Produto de qualidade excelente,2017-01-31 00:00:00,2017-02-01 16:56:49
...,...,...,...,...,...,...,...
99130,2d63075ea39da3d2772ac263935cbcea,ec95bda03fcd25491f6e0142ef318ee8,4,NaN,Produto de muito boa qualidade!,2017-02-23 00:00:00,2017-02-24 13:55:07
99161,49bcf2440b3b9f881220ba5e56092103,fde5931c072d09a2a89da86b20ab0451,5,NaN,NaN,2017-03-25 00:00:00,2017-03-29 02:08:55
99172,314d2e4c14be2030c24c3f29ff3740a7,e3c4b2d7022588a02583a79b3f405632,5,NaN,Satisfeita,2017-04-22 00:00:00,2017-04-22 10:38:17
99209,aa711ac8a41557897f94dd7cd1846bdd,ef8e8348ba291917542268f900fac505,5,NaN,NaN,2017-03-08 00:00:00,2017-03-09 13:34:57
99212,3ea12859f456855149b564d1a221f87a,f62f01ec64c6b221f926ba560907d8f7,3,NaN,NaN,2017-04-05 00:00:00,2017-04-05 09:42:58

In [214]:
os.makedirs("New_Raw_Data/Orders_Q1_2017", exist_ok=True)
Orders_Q1_2017.to_csv("New_Raw_Data/Orders_Q1_2017/Orders_Q1_2017.csv")

In [215]:
Customers_Q1_2017.to_csv("New_Raw_Data/Orders_Q1_2017/Customers_Q1_2017.csv")

In [216]:
Order_items_Q1_2017.to_csv("New_Raw_Data/Orders_Q1_2017/order_items_Q1_2017.csv")

In [217]:
Order_Payments_Q1_2017.to_csv("New_Raw_Data/Orders_Q1_2017/Order_Payments_Q1_2017.csv")

In [218]:
Order_reviews_Q1_2017.to_csv("New_Raw_Data/Orders_Q1_2017/order_reviews_Q1_2017.csv")

In [219]:
Orders_Q2_2017=Orders_df[(Orders_df["year"]==2017) & (Orders_df["quarter"]==2)]

In [220]:
Customers_ids=Orders_Q2_2017["customer_id"]
Customers_ids

6        ed0271e0b7da060a393796590e7b737a
7        9bdf08b4b3b52b5526ff42d37d47f222
10       494dded5b201313c64ed7f100595b95c
40       ddaff536587109b89777e0353215e150
45       4f28355e5c17a4a42d3ce2439a1d4501
                       ...
99392    8b764335e86e1a8f8d3db9f119e03a79
99406    d32034dfc685b1ae15dd4c78eace868e
99408    166478efeed4f9a861164b4ff5acfe8b
99420    6f2cf56878f7f82151b0ad02590192c0
99426    9e870ea67399650e8c3545a25d13e4d0
Name: customer_id, Length: 9349, dtype: object

In [221]:
Customers_Q2_2017=Customers_df[Customers_df["customer_id"].isin(Customers_ids)]
Customers_Q2_2017

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
18,9b8ce803689b3562defaad4613ef426f,7f3a72e8f988c6e735ba118d54f47458,5416,sao paulo,SP
23,237098a64674ae89babdc426746260fc,4390ddbb6276a66ff1736a6710205dca,82820,curitiba,PR
27,6e359a57a91f84095cc64e1b351aef8c,2e6a42a9b5cbb0da62988694f18ee295,4571,sao paulo,SP
33,b2bed119388167a954382cca36c4777f,e079b18794454de9d2be5c12b4392294,27525,resende,RJ
...,...,...,...,...,...
99398,059f60d3b37627f51e73eec500dfa1a8,db634985638ec4b6abf8734d7adde1ab,82800,curitiba,PR
99400,b6ab7cabd5b094d098e1a1557a6d3f0d,a2325193ac2e95b805642e3100f80af3,11630,ilhabela,SP
99419,a1b5ca506b592bb72d4caadcbfe71385,c811311629fd3d76f5ca5eeb2abfa7e8,17511,marilia,SP
99424,e5ed7280cd1a3ac2ba29fd6650d8867c,206e64e8af2633a2ebe158a7fcb860db,8560,poa,SP
99430,27b9b32173455ef32167540451749d0b,277490f0d435b602fe4475d4b89e9181,6727,cotia,SP

In [222]:
Orders_ids=Orders_Q2_2017["order_id"]
Orders_ids

6        136cce7faa42fdb2cefd53fdc79a6098
7        6514b8ad8028c9f2cc2374ded245783f
10       e6ce16cb79ec1d90b1da9085a6118aeb
40       1e7aff52cdbb2451ace09d0f848c3699
45       6ebaec694d7025e2ad4a05dba887c032
                       ...
99392    33baefa752f2d98a008d4330d306d3db
99406    7fd85cb0143de098a4c5ab5a57bfbd91
99408    f6f9344efc918f1e00ab84c014aa21d7
99420    f9e3402be5a5ea63344347582ca9f45f
99426    7cc85185736ea7f2d8bc09af7a47cab7
Name: order_id, Length: 9349, dtype: object

In [223]:
Order_items_Q2_2017=Order_Items_df[Order_Items_df["order_id"].isin(Orders_ids)]
Order_items_Q2_2017

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
5,00048cc3ae777c65dbb7d2a0634bc1ea,1,ef92defde845ab8450f9d70c526ef70f,6426d21aca402a131fc0a5d0960a3c90,2017-05-23 03:55:27,21.90,12.69
35,0014ae671de39511f7575066200733b7,1,23365beed316535b4105bd800c46670e,92eb0f42c21942b6552362b9b114707d,2017-05-29 03:15:24,16.50,14.10
38,0016dfedd97fc2950e388d2971d718c7,1,4089861a1bd4685da70bddd6b4f974f1,a35124e2d763d7ca3fbe3b97d143200f,2017-05-05 10:05:12,49.75,20.80
39,0017afd5076e074a48f1f1a4c7bac9c5,1,fe59a1e006df3ac42bf0ceb876d70969,25c5c91f63607446a97b143d2d535d31,2017-04-24 22:25:19,809.10,44.29
...,...,...,...,...,...,...,...
112611,ffea5b26be781da4c215c0feb484f4fd,1,ac23312b29784c30304f2ec719891690,066a6914e1ebf3ea95a216c73a986b91,2017-06-08 17:05:17,119.99,20.08
112621,ffef98cd5ecdc992fefbd967549520dd,1,11fd9d7ba552e1d28872e008acf1e050,cb8bcce248bb1fb274ba762d8b971456,2017-07-06 03:15:21,139.90,13.11
112627,fff2e9e3aa8644e19710216b4ef53ab2,1,7340a3839a1de1e99d149b8cf052a2ec,4a3ca9315b744ce9f8e9374361493884,2017-06-01 02:42:42,69.90,16.25
112632,fff7c4452f050315db1b3f24d9df5fcd,1,dd469c03ad67e201bc2179ef077dcd48,7e93a43ef30c4f03f38b393420bc753a,2017-06-07 17:05:23,736.00,20.91
112638,fffb0b1a50e65c449020434fa835e078,1,e7be84ea9462aac5e2b0b08eb35ba7f1,36a968b544695394e4e9d7572688598f,2017-04-28 16:45:12,4.90,10.96

In [224]:
Order_Payments_Q2_2017=Order_Payments_df[Order_Payments_df["order_id"].isin(Orders_ids)]
Order_Payments_Q2_2017

,order_id,payment_sequential,payment_type,payment_installments,payment_value
6,771ee386b001f06208a7419e4fc1bbd7,1,credit_card,1,81.16
7,3d7239c394a212faae122962df514ac7,1,credit_card,3,51.84
14,769214176682788a92801d8907fa1b40,1,credit_card,4,105.28
29,b69b9260e79a0da00e15f48de1bd2524,1,boleto,1,283.34
76,97c111c4f22dfa1089a9c0b5338dcc79,1,credit_card,3,44.01
...,...,...,...,...,...
103849,9a87b7f9b871b4725233e41e08811caa,1,credit_card,3,93.97
103863,4b186efcda6f283e9c4a71332f6d3ad0,1,credit_card,1,57.51
103864,c11717d999ffc510a6441df946f0a94d,1,credit_card,9,96.90
103866,387c2c33e495538e94878a500bf8e6d5,1,credit_card,1,87.58
103869,c9b01bef18eb84888f0fd071b8413b38,1,credit_card,6,238.16

In [225]:
Order_reviews_Q2_2017=Order_Reviews_df[Order_Reviews_df["order_id"].isin(Orders_ids)]
Order_reviews_Q2_2017

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
6,07f9bee5d1b850860defd761afa7ff16,e48aa0d2dcec3a2e87348811bcfdf22b,5,NaN,NaN,2017-07-16 00:00:00,2017-07-18 19:30:34
8,a3f6f7f6f433de0aefbb97da197c554c,9c214ac970e84273583ab523dfafd09b,5,NaN,NaN,2017-05-17 00:00:00,2017-05-18 12:05:37
14,9a0abbb668bafb95a6d2b05db43284c4,d7bd0e4afdf94846eb73642b4e3e75c3,3,NaN,NaN,2017-04-30 00:00:00,2017-05-03 00:02:22
25,66e4430c5bc6b7e3773886bf1c14d912,84cec4f65c7a4f2f54c294a30224a594,5,NaN,NaN,2017-06-23 00:00:00,2017-06-27 00:52:02
...,...,...,...,...,...,...,...
99184,6cf47345d15e054dd6df872e929bdb27,54e6829fe81bc86cf88b12e6d07ea298,1,NaN,NaN,2017-06-08 00:00:00,2017-06-08 22:52:39
99190,70c4e8609905a1520bc1ab23945453a2,8173609cc6bf4ac5c1e577223ae83522,4,NaN,NaN,2017-04-08 00:00:00,2017-04-09 16:23:52
99193,d57774fa9cf83a0a034c62890e1d93d2,2bf1d83ac1f9e3bb2a9c497d3de0e866,4,NaN,NaN,2017-06-29 00:00:00,2017-06-30 11:22:07
99211,8eff18f2dba837af3a03329b574f12ec,ae89f3c648838ad99ed4616f05b2662a,5,NaN,NaN,2017-06-20 00:00:00,2017-06-21 00:19:29
99223,efe49f1d6f951dd88b51e6ccd4cc548f,90531360ecb1eec2a1fbb265a0db0508,1,NaN,"meu produto chegou e ja tenho que devolver, po...",2017-07-03 00:00:00,2017-07-03 21:01:49

In [226]:
os.makedirs("New_Raw_Data/Orders_Q2_2017", exist_ok=True)
Orders_Q2_2017.to_csv("New_Raw_Data/Orders_Q2_2017/Orders_Q2_2017.csv")

In [227]:
Customers_Q2_2017.to_csv("New_Raw_Data/Orders_Q2_2017/Customers_Q2_2017.csv")

In [228]:
Order_items_Q2_2017.to_csv("New_Raw_Data/Orders_Q2_2017/order_items_Q2_2017.csv")

In [229]:
Order_Payments_Q2_2017.to_csv("New_Raw_Data/Orders_Q2_2017/Order_Payments_Q2_2017.csv")

In [230]:
Order_reviews_Q2_2017.to_csv("New_Raw_Data/Orders_Q2_2017/order_reviews_Q2_2017.csv")

In [231]:
Orders_Q3_2017=Orders_df[(Orders_df["year"]==2017) & (Orders_df["quarter"]==3)]

In [232]:
Customers_ids=Orders_Q3_2017["customer_id"]
Customers_ids

5        503740e9ca751ccdda7ba28e9ab8f608
9        31ad1d1b63eb9962463f764d4e6e0c9d
11       7711cf624183d843aafe81855097bc37
20       d2b091571da224a1b36412c18bc3bbfe
30       456dc10730fbdba34615447ea195d643
                       ...
99399    b3e43e654b4d35baf3840feca1135f85
99410    dce0014426964924f9564758e4fadcbf
99414    609b9fb8cad4fe0c7b376f77c8ab76ad
99421    3803547f820b1e10b7ad9c7985f06753
99438    1aa71eb042121263aafbe80c1b562c9c
Name: customer_id, Length: 12642, dtype: object

In [233]:
Customers_Q3_2017=Customers_df[Customers_df["customer_id"].isin(Customers_ids)]
Customers_Q3_2017

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
5,879864dab9bc3047522c92c82e1212b8,4c93744516667ad3b8f1fb645a3116a4,89254,jaragua do sul,SC
12,b2d1536598b73a9abd18e0d75d92f0a3,918dc87cd72cd9f6ed4bd442ed785235,18682,lencois paulista,SP
20,154c4ded6991bdfa3cd249d11abf4130,e607ede0e63436308660236f5a52da5e,88034,florianopolis,SC
30,261cb4f92498ca05d5bd1a327a261d9c,424aca6872c5bab80780a8dec03b7516,12235,sao jose dos campos,SP
37,54f755c3fd2709231f9964a1430c5218,40febde16f4718a5def537786473b0be,93415,novo hamburgo,RS
...,...,...,...,...,...
99372,7ba8bdd359b397be54d6e280b75b0987,9b03f2721fb73962781bae9322b0c071,35650,pitangui,MG
99376,0b7a30ba373aeb55cf28add5b5477956,8c8173e547e020f411aa55b2fceed861,87145,paicandu,PR
99381,661ab54307d752dcc15fd85d731c0999,a10c0d1e68e919e3d91ed940a0ba6aed,20751,rio de janeiro,RJ
99384,0d7da1d5507a67dbb512b53744e775e9,a5ba329297100ea689fa263768b35b8b,95020,caxias do sul,RS
99392,94747b8a0c77eb8947fecdfa5b717435,81720bfb69887fe95390723af9748e9f,22780,rio de janeiro,RJ

In [234]:
Orders_ids=Orders_Q3_2017["order_id"]
Orders_ids

5        a4591c265e18cb1dcee52889e2d8acc3
9        e69bfb5eb88e0ed6a785585b27e16dbf
11       34513ce0c4fab462a55830c0989c7edb
20       203096f03d82e0dffbc41ebc2e2bcfb7
30       f70a0aff17df5a6cdd9a7196128bd354
                       ...
99399    226dda5620db063cd962833766480273
99410    71c4b7b8844a031b7db8ca41c41d4aae
99414    e8fd20068b9f7e6ec07068bb7537f781
99421    6f46d42016226f77893ed3978d6903d0
99438    83c1379a015df1e13d02aae0204711ab
Name: order_id, Length: 12642, dtype: object

In [235]:
Order_items_Q3_2017=Order_Items_df[Order_Items_df["order_id"].isin(Orders_ids)]
Order_items_Q3_2017

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
18,000c3e6612759851cc3cbb4b83257986,1,b50c950aba0dcead2c48032a690ce817,218d46b86c1881d022bce9c68a7d4b15,2017-08-21 03:33:13,99.00,13.71
24,0010b2e5201cc5f1ae7e9c6cc8f5bd00,1,5a419dbf24a8c9718fe522b81c69f61a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-09-15 18:04:37,48.90,16.60
25,00119ff934e539cf26f92b9ef0cdfed8,1,21b1c2f67a9aafb5af0eb06c13b9dbda,c864036feaab8c1659f65ea4faebe1da,2017-08-11 00:35:12,219.90,16.98
55,0020a222f55eb79a372d0efee3cca688,1,e19ddcc85537b41f22116c8d5425ef46,8a32e327fe2c1b3511609d81aaf9f042,2017-08-21 03:03:44,29.99,15.10
...,...,...,...,...,...,...,...
112618,ffed7e90414c1477a6b92554661d465f,1,550dc4417c636abc04c71404342de695,25c5c91f63607446a97b143d2d535d31,2017-08-04 14:55:20,149.90,16.81
112623,ffefb169ddf34cecc0622a6d3cc387f8,1,601a360bd2a916ecef0e88de72a6531a,7a67c85e85bb2ce8582c35f2203ad736,2017-07-06 19:35:09,129.99,12.11
112630,fff6889749958e42b47a7977a4cf0ea0,1,75f6a4f019ec1322758d53b2fee2cc12,058cb5aeb36d7c0fcae20fc85d5e0a59,2017-10-01 22:56:15,92.00,31.60
112631,fff6b8ca971f8e3ec822e99d0f2d3d21,1,9afaad66aca8b0c79e4f084a89c9c92b,42bde9fef835393bb8a8849cb6b7f245,2017-09-21 12:04:29,199.00,16.83
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72

In [236]:
Order_Payments_Q3_2017=Order_Payments_df[Order_Payments_df["order_id"].isin(Orders_ids)]
Order_Payments_Q3_2017

,order_id,payment_sequential,payment_type,payment_installments,payment_value
9,0573b5e23cbd798006520e1d5b4c6714,1,boleto,1,51.95
13,cf95215a722f3ebf29e6bbab87a29e61,1,credit_card,5,102.66
20,5a1f6d22f7dfb061ef29216b9af687a1,1,credit_card,4,47.69
24,8cd68144cdb62dc0d60848cf8616d2a4,1,boleto,1,330.66
30,f45074ae38f2e01d9b854ec8d40362ff,1,credit_card,1,13.78
...,...,...,...,...,...
103841,ff269db61cf306545ee8f5ada41a4a3f,1,credit_card,1,74.16
103853,bc2b2f5f5aad2762906c62abe09d5677,1,credit_card,1,114.13
103854,bd1d2815016a0d22c926101c1c99d140,1,boleto,1,94.99
103876,0872d0faafe0cb56e6f2c594cca1522c,1,credit_card,2,127.92
103882,7b905861d7c825891d6347454ea7863f,1,credit_card,2,96.80

In [237]:
Order_reviews_Q3_2017=Order_Reviews_df[Order_Reviews_df["order_id"].isin(Orders_ids)]
Order_reviews_Q3_2017

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
18,fdbdb2629a7cde0f66657acc92084e7f,70a752414a13d09cc1f2b437b914b28e,3,NaN,NaN,2017-09-29 00:00:00,2017-10-02 01:12:49
20,a2ff510ca4e059c3fefc7a7866571f6f,a9953b2f0b1665ac7586cc5a6ac8f58c,4,NaN,NaN,2017-10-06 00:00:00,2017-10-08 22:36:05
23,7bcb3c758c67f23638262c731493e848,7c9956750739a47dba7a6928ba2f0245,5,NaN,NaN,2017-09-09 00:00:00,2017-10-17 02:25:47
31,6a18a4001ae7fd911b3b9fb13686d105,8ba3f3a9292fbc22a8b7dff752bbcd37,5,NaN,NaN,2017-07-19 00:00:00,2017-07-20 10:38:48
35,c0f4c8301f8c29d6f53d239e194bb4c2,04db86e3493b3724ac4bd3c9a397e23c,5,NaN,NaN,2017-09-12 00:00:00,2017-09-13 14:33:49
...,...,...,...,...,...,...,...
99148,997072275287e609ee8c55c3f6e5bb14,0da9ad216b1827c67a72f0c852666c40,5,NaN,"Amei , indico a todos do ML\r\n",2017-07-19 00:00:00,2017-07-21 14:31:50
99151,bbdce7ec5954a32727f31c0bc393c10f,3236504a0e2b1bceb65d32a38f5d79a9,5,NaN,NaN,2017-09-21 00:00:00,2017-09-22 02:53:34
99156,c4279842b4a17304a809f750aa29d813,60498cfabd11f25114990225793f3ea0,4,NaN,NaN,2017-09-09 00:00:00,2017-09-10 00:55:17
99157,dca7f3bc4be65b02ec9ccb10f62d3b94,9d14efbb0c50e58aa2098e5338df7575,5,NaN,NaN,2017-09-20 00:00:00,2017-09-21 16:33:58
99191,ed81d320e16c5999ff55348dce57d02b,daa7bd63b41e09a4d28579829649e6a2,5,NaN,Gostei muito.\r\nÉ a segunda vez que compro o ...,2017-08-20 00:00:00,2017-08-21 15:27:32

In [238]:
os.makedirs("New_Raw_Data/Orders_Q3_2017", exist_ok=True)
Orders_Q3_2017.to_csv("New_Raw_Data/Orders_Q3_2017/Orders_Q3_2017.csv")

In [239]:
Customers_Q3_2017.to_csv("New_Raw_Data/Orders_Q3_2017/Customers_Q3_2017.csv")

In [240]:
Order_items_Q3_2017.to_csv("New_Raw_Data/Orders_Q3_2017/order_items_Q3_2017.csv")

In [241]:
Order_Payments_Q3_2017.to_csv("New_Raw_Data/Orders_Q3_2017/Order_Payments_Q3_2017.csv")

In [242]:
Order_reviews_Q3_2017.to_csv("New_Raw_Data/Orders_Q3_2017/order_reviews_Q3_2017.csv")

In [243]:
Orders_Q4_2017=Orders_df[(Orders_df["year"]==2017) & (Orders_df["quarter"]==4)]

In [244]:
Customers_ids=Orders_Q4_2017["customer_id"]
Customers_ids

0        9ef432eb6251297304e76186b10a928d
3        f88197465ea7920adcdbec7375364d82
17       3187789bec990987628d7a9beb4dd6ac
18       059f7fc5719c7da6cbafe370971a8d70
19       7f8c8b9c2ae27bf3300f670c3d478be8
                       ...
99424    f00bb12620b7b232233cace1b229db18
99429    2e96fa6d55b9732013caed9866e2552d
99431    8e1ec396e317ff4c82a03ce16a0c3eb3
99432    a2f7428f0cafbc8e59f20e1444b67315
99433    da2124f134f5dfbce9d06f29bdb6c308
Name: customer_id, Length: 17848, dtype: object

In [245]:
Customers_Q4_2017=Customers_df[Customers_df["customer_id"].isin(Customers_ids)]
Customers_Q4_2017

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
7,5e274e7a0c3809e14aba7ad5aae0d407,57b2a98a409812fe9618067b6b8ebe4f,35182,timoteo,MG
10,9fb35e4ed6f0a14a4977cd9aea4042bb,2a7745e1ed516b289ed9b29c7d0539a5,39400,montes claros,MG
19,49d0ea0986edde72da777f15456a0ee0,3e6fd6b2f0d499456a6a6820a40f2d79,68485,pacaja,PA
21,690172ab319622688d3b4df42f676898,a96d5cfa0d3181817e2b946f921ea021,74914,aparecida de goiania,GO
28,e0eea8f69a457b3f1fa246e44c9ebefd,4d221875624017bc47b4d1ce7314a5b7,29311,cachoeiro de itapemirim,ES
...,...,...,...,...,...
99426,935993f47af1ed7d0715c26b686341c5,4452b8ef472646c4cc042cb31a291f3b,12236,sao jose dos campos,SP
99429,1ed0c832c2dd99570a59260e71768bdf,82d46759af0369aad49084bacf85a6c3,37610,bom repouso,MG
99435,7fe2e80252a9ea476f950ae8f85b0f8f,4b5820135d360a45552b5163835b1d89,35500,divinopolis,MG
99439,56b18e2166679b8a959d72dd06da27f9,73c2643a0a458b49f58cea58833b192e,92120,canoas,RS
99440,274fa6071e5e17fe303b9748641082c8,84732c5050c01db9b23e19ba39899398,6703,cotia,SP

In [246]:
Orders_ids=Orders_Q4_2017["order_id"]
Orders_ids

0        e481f51cbdc54678b7cc49136f2d6af7
3        949d5b44dbf5de918fe9c16f97b45f8a
17       116f0b09343b49556bbad5f35bee0cdf
18       85ce859fd6dc634de8d2f1e290444043
19       83018ec114eee8641c97e08f7b4e926f
                       ...
99424    6ec4642f9993cc34f826cfb9068e5a2f
99429    0e4b26f1fb99fc0f0472dd5f403d36d4
99431    b0f4af5c1b06e24fef510703bfe9f0a6
99432    cfa78b997e329a5295b4ee6972c02979
99433    9115830be804184b91f5c00f6f49f92d
Name: order_id, Length: 17848, dtype: object

In [247]:
Order_items_Q4_2017=Order_Items_df[Order_Items_df["order_id"].isin(Orders_ids)]
Order_items_Q4_2017

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
6,00054e8431b9d7675808bcb819fb4a32,1,8d4f2bb7e93e6710a28f34fa83ee7d28,7040e82f899a04d1b434b795a43b4617,2017-12-14 12:10:31,19.90,11.85
21,000e906b789b55f64edcb1f84030f90d,1,57d79905de06d8897872c551bfd09358,ea8482cd71df3c1969d7b9473ff13abc,2017-11-27 19:09:02,21.99,11.85
29,0013503b13da1eac686219390b7d641b,1,38afdf723b95d455b418a0f57d623c6b,1554a68530182680ad5c8b042c3ab563,2017-12-13 03:16:36,119.90,17.32
30,00137e170939bba5a3134e2386413108,1,672e757f331900b9deea127a2a7b79fd,e59aa562b9f8076dd550fcddf0e73491,2017-11-30 06:30:55,397.00,24.65
32,00143d0f86d6fbd9f9b38ab440ac16f5,1,e95ee6822b66ac6058e2e4aff656071a,a17f621c590ea0fab3d5d883e1630ec6,2017-10-20 16:07:52,21.33,15.10
...,...,...,...,...,...,...,...
112640,fffb9224b6fc7c43ebb0904318b10b5f,1,43423cdffde7fda63d0414ed38c11a73,b1fc4f64df5a0e8b6913ab38803c57a9,2017-11-03 02:55:58,55.00,34.19
112641,fffb9224b6fc7c43ebb0904318b10b5f,2,43423cdffde7fda63d0414ed38c11a73,b1fc4f64df5a0e8b6913ab38803c57a9,2017-11-03 02:55:58,55.00,34.19
112642,fffb9224b6fc7c43ebb0904318b10b5f,3,43423cdffde7fda63d0414ed38c11a73,b1fc4f64df5a0e8b6913ab38803c57a9,2017-11-03 02:55:58,55.00,34.19
112643,fffb9224b6fc7c43ebb0904318b10b5f,4,43423cdffde7fda63d0414ed38c11a73,b1fc4f64df5a0e8b6913ab38803c57a9,2017-11-03 02:55:58,55.00,34.19
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95

In [248]:
Order_Payments_Q4_2017=Order_Payments_df[Order_Payments_df["order_id"].isin(Orders_ids)]
Order_Payments_Q4_2017

,order_id,payment_sequential,payment_type,payment_installments,payment_value
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
10,d88e0d5fa41661ce03cf6cf336527646,1,credit_card,8,188.73
11,2480f727e869fdeb397244a21b721b67,1,credit_card,1,141.90
25,5cfd514482e22bc992e7693f0e3e8df7,2,voucher,1,45.17
...,...,...,...,...,...
103871,20824837882dd673707e0adfcaec1bc1,1,credit_card,1,84.23
103873,40ec2cf5cb1eb0bf1ea2b117552fecb5,1,credit_card,2,90.28
103878,2e3d96522c8c378d4135c12a65c977aa,1,credit_card,4,47.62
103883,32609bbb3dd69b3c066a6860554a77bf,1,credit_card,1,47.77
103885,28bbae6599b09d39ca406b747b6632b1,1,boleto,1,191.58

In [249]:
Order_reviews_Q4_2017=Order_Reviews_df[Order_Reviews_df["order_id"].isin(Orders_ids)]
Order_reviews_Q4_2017

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
10,c9cfd2d5ab5911836ababae136c3a10c,cdf9aa68e72324eeb25c7de974696ee2,5,NaN,NaN,2017-12-23 00:00:00,2017-12-26 14:36:03
11,96052551d87e5f62e6c9f6974ec392e9,3d374c9e46530bb5ed4a7648915306a6,5,NaN,NaN,2017-12-19 00:00:00,2017-12-20 10:25:22
16,9314d6f9799f5bfba510cc7bcd468c01,0dacf04c5ad59fd5a0cc1faa07c34e39,2,NaN,"GOSTARIA DE SABER O QUE HOUVE, SEMPRE RECEBI E...",2018-01-18 00:00:00,2018-01-20 21:25:45
24,0e0190b9db53b689b285d3f3916f8441,79832b7cb59ac6f887088ffd686e1d5e,5,NaN,obrigado pela atençao amim dispensada,2017-12-01 00:00:00,2017-12-09 22:58:58
26,bf566b3910c328733baf7fca7d2be041,a59a15e4b6085c752d338431dc68d464,4,NaN,NaN,2017-11-01 00:00:00,2017-11-01 20:25:30
...,...,...,...,...,...,...,...
99198,445a7bd5ce7f7bc9c28a5844c2466acc,2d687102eef8e4949a9d2af49e8fa946,3,NaN,NaN,2017-12-19 00:00:00,2017-12-28 16:51:12
99205,98fffa80dc9acbde7388bef1600f3b15,d398e9c82363c12527f71801bf0e6100,4,NaN,para este produto recebi de acordo com a compr...,2017-11-29 00:00:00,2017-11-30 15:52:51
99206,6c5fa14b1cb0ede918c75b1fabb222a5,10a3f7e9bf88b7dc86a767fd278e5bd2,5,NaN,NaN,2017-11-21 00:00:00,2017-11-23 08:28:00
99217,c6b270c61f67c9f7cb07d84ea8aeaf8b,48f7ee67313eda32bfcf5b9c1dd9522d,5,NaN,NaN,2017-12-13 00:00:00,2017-12-14 11:09:36
99220,f3897127253a9592a73be9bdfdf4ed7a,22ec9f0669f784db00fa86d035cf8602,5,NaN,NaN,2017-12-09 00:00:00,2017-12-11 20:06:42

In [250]:
os.makedirs("New_Raw_Data/Orders_Q4_2017", exist_ok=True)
Orders_Q4_2017.to_csv("New_Raw_Data/Orders_Q4_2017/Orders_Q4_2017.csv")

In [251]:
Customers_Q4_2017.to_csv("New_Raw_Data/Orders_Q4_2017/Customers_Q4_2017.csv")

In [252]:
Order_items_Q4_2017.to_csv("New_Raw_Data/Orders_Q4_2017/order_items_Q4_2017.csv")

In [253]:
Order_Payments_Q4_2017.to_csv("New_Raw_Data/Orders_Q4_2017/Order_Payments_Q4_2017.csv")

In [254]:
Order_reviews_Q4_2017.to_csv("New_Raw_Data/Orders_Q4_2017/order_reviews_Q4_2017.csv")

In [255]:
Orders_Q1_2018=Orders_df[(Orders_df["year"]==2018) & (Orders_df["quarter"]==1)]

In [256]:
Customers_ids=Orders_Q1_2018["customer_id"]
Customers_ids

4        8ab97904e6daea8866dbdbc4fb7aad2c
14       3df704f53d3f1d4818840b34ec672a9f
16       738b086814c6fcc74b8cc583f8516ee3
21       4fa1cd166fa598be6de80fa84eaade43
22       72ae281627a6102d9b3718528b420f8a
                       ...
99425    82ddfcf9438b0cd1117b55ac33184df8
99430    7b270ebc87c25c8404348c10ff80a80e
99437    1fca14ff2861355f6e5f14306ff977a7
99439    b331b74b18dc79bcdf6532d51e1637c1
99440    edb027a75a1449115f6b43211ae02a24
Name: customer_id, Length: 21208, dtype: object

In [257]:
Customers_Q1_2018=Customers_df[Customers_df["customer_id"].isin(Customers_ids)]
Customers_Q1_2018

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
6,fd826e7cf63160e536e0908c76c3f441,addec96d2e059c80c30fe6871d30d177,4534,sao paulo,SP
8,5adf08e34b2e993982a47070956c5c65,1175e95fb47ddff9de6b2b06188f7e0d,81560,curitiba,PR
9,4b7139f34592b3a31687243a302fa75b,9afe194fb833f79e300e37e580171f22,30575,belo horizonte,MG
...,...,...,...,...,...
99417,b7c889215de76857c7967c1011125d2d,522e244a96d13876c5bac4985a8d5075,82410,curitiba,PR
99418,30c96385d694acb8aa2dc0df1770120b,b96d6a178adbabf269fd843b37327798,26112,belford roxo,RJ
99421,5eef6cce1f34954c9e7004332388ccc7,5a1680640123fc80e801301a2fb57395,11045,santos,SP
99425,0a7db3996b88954c7aa763b5dd621d5b,15637b62dfa4c5a9df846b22beef0994,52090,recife,PE
99432,f255d679c7c86c24ef4861320d5b7675,d111b06b6f3a2add0d2241325f65b5ca,13500,rio claro,SP

In [258]:
Orders_ids=Orders_Q1_2018["order_id"]
Orders_ids

4        ad21c59c0840e6cb83a9ceb5573f8159
14       432aaf21d85167c2c86ec9448c4e42cc
16       403b97836b0c04a622354cf531062e5f
21       f848643eec1d69395095eb3840d2051e
22       2807d0e504d6d4894d41672727bc139f
                       ...
99425    d692ef54145c9cb3322ec2e5508aa3f4
99430    c81f74e50f0496fa39716cc77cacd460
99437    63943bddc261676b46f01ca7ac2f7bd8
99439    11c177c8e97725db2631073c19f07b62
99440    66dea50a8b16d9b4dee7af250b4be1a5
Name: order_id, Length: 21208, dtype: object

In [259]:
Order_items_Q1_2018=Order_Items_df[Order_Items_df["order_id"].isin(Orders_ids)]
Order_items_Q1_2018

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
8,0005a1a1728c9d785b8e2b08b904576c,1,310ae3c140ff94b03219ad0adc3c778f,a416b6a846a11724393025641d4edd5e,2018-03-26 18:31:29,145.95,11.65
10,00061f2a7bc09da83e415a52dc8a4af1,1,d63c1011f49d98b976c352955b1c4bea,cc419e0650a3c5ba77189a1882b7556a,2018-03-29 22:28:09,59.99,8.88
13,0008288aa423d2a3f00fcb17cd7d8719,1,368c6c730842d78016ad823897a372db,1f50f920176fa81dab994f9023523100,2018-02-21 02:55:52,49.90,13.37
14,0008288aa423d2a3f00fcb17cd7d8719,2,368c6c730842d78016ad823897a372db,1f50f920176fa81dab994f9023523100,2018-02-21 02:55:52,49.90,13.37
...,...,...,...,...,...,...,...
112626,fff2cdc825f9fc0ba3c04227cfa02303,1,044f05bc9de36e8a693a83e4bc79dd0d,ea8482cd71df3c1969d7b9473ff13abc,2018-02-08 02:52:42,24.99,25.63
112629,fff60e5408a9dd1e92ee30023052af30,1,1a405418406359cc2b8815f93bf359c2,4d6d651bd7684af3fffabd5f08d12e5a,2018-02-05 10:55:55,129.90,18.80
112634,fff8287bbae429a99bb7e8c21d151c41,1,bee2e070c39f3dd2f6883a17a5f0da45,4e922959ae960d389249c378d1c939f5,2018-03-27 12:29:22,180.00,48.14
112635,fff8287bbae429a99bb7e8c21d151c41,2,bee2e070c39f3dd2f6883a17a5f0da45,4e922959ae960d389249c378d1c939f5,2018-03-27 12:29:22,180.00,48.14
112639,fffb2ef8874127f75b52b643880fd7e0,1,ebceb9726cf5c6187b48e17fe58747b0,609e1a9a6c2539919b8205cf7c4e6ff0,2018-04-09 05:08:33,17.90,22.06

In [260]:
Order_Payments_Q1_2018=Order_Payments_df[Order_Payments_df["order_id"].isin(Orders_ids)]
Order_Payments_Q1_2018

,order_id,payment_sequential,payment_type,payment_installments,payment_value
15,12e5cfe0e4716b59afb0e0f4a3bd6570,1,credit_card,10,157.45
18,8ac09207f415d55acff302df7d6a895c,1,credit_card,4,244.15
22,adfbf6c2a620196f9a3ec747491c72b7,1,credit_card,4,67.50
45,0e0441786430b7cfcd0d91f822ea4c99,1,credit_card,1,121.49
46,6ffb3f1686bceae3466facf7e02ce3fb,1,credit_card,1,32.00
...,...,...,...,...,...
103865,f593228a7a25e9633ff78a4ce0d0d4cc,1,credit_card,8,165.80
103874,d41f1036712e18ee525939d08b7a1c98,1,credit_card,1,3.57
103877,3531718b24dfd5022fb0d101e10e33b9,1,credit_card,1,194.11
103880,7159096c5aa9be77f7f0c26c01ee9793,1,credit_card,4,280.65
103881,0406037ad97740d563a178ecc7a2075c,1,boleto,1,363.31

In [261]:
Order_reviews_Q1_2018=Order_Reviews_df[Order_Reviews_df["order_id"].isin(Orders_ids)]
Order_reviews_Q1_2018

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53
12,4b49719c8a200003f700d3d986ea1a19,9d6f15f95d01e79bd1349cc208361f09,4,NaN,"Mas um pouco ,travando...pelo valor ta Boa.\r\n",2018-02-16 00:00:00,2018-02-20 10:52:22
...,...,...,...,...,...,...,...
99200,2ee221b28e5b6fceffac59487ed39348,f2d12dd37eaef72ed7b1186b2edefbcd,2,Foto enganosa,Foto muito diferente principalmente a graninha...,2018-03-28 00:00:00,2018-05-25 01:23:26
99201,107fb39001ec82a9265b73d65e5ce47f,795b0bc608229d7cb45e79030bfa7d4b,5,NaN,NaN,2018-01-24 00:00:00,2018-01-24 11:27:03
99203,5085bc489aa6b58a29c4f922d59ff826,18ed848509774f56cc8c1c0a1903ad7f,2,NaN,Tive um problema na entrega em que o correio c...,2018-02-21 00:00:00,2018-02-23 11:43:12
99208,df5fae90e85354241d5d64a8955b2b09,509b86c65fe4e2ad5b96408cfef9755e,5,NaN,Entregou dentro do prazo. O produto chegou em ...,2018-02-07 00:00:00,2018-02-19 19:47:23
99221,b3de70c89b1510c4cd3d0649fd302472,55d4004744368f5571d1f590031933e4,5,NaN,"Excelente mochila, entrega super rápida. Super...",2018-03-22 00:00:00,2018-03-23 09:10:43

In [262]:
os.makedirs("New_Raw_Data/Orders_Q1_2018", exist_ok=True)
Orders_Q1_2018.to_csv("New_Raw_Data/Orders_Q1_2018/Orders_Q1_2018.csv")

In [263]:
Customers_Q1_2018.to_csv("New_Raw_Data/Orders_Q1_2018/Customers_Q1_2018.csv")

In [264]:
Order_items_Q1_2018.to_csv("New_Raw_Data/Orders_Q1_2018/order_items_Q1_2018.csv")

In [265]:
Order_Payments_Q1_2018.to_csv("New_Raw_Data/Orders_Q1_2018/Order_Payments_Q1_2018.csv")

In [266]:
Order_reviews_Q1_2018.to_csv("New_Raw_Data/Orders_Q1_2018/order_reviews_Q1_2018.csv")

In [267]:
Orders_Q2_2018=Orders_df[(Orders_df["year"]==2018) & (Orders_df["quarter"]==2)]

In [268]:
Customers_ids=Orders_Q2_2018["customer_id"]
Customers_ids

12       d3e3b74c766bc6214e0c830b17ee2341
15       3b6828a50ffe546942b7a473d70ac0fc
26       7e20bf5ca92da68200643bda76c504c6
28       cce89a605105b148387c52e286ac8335
31       52142aa69d8d0e1247ab0cada0f76023
                       ...
99413    20b927d23e84dfaa333eb4aea6615084
99416    42b0671b440d1f2527bddd8b723e0a0c
99422    a046c690e0564ffde0ce611b5eee2c30
99427    cf97e9cf454480b303de6736ddd15fd6
99428    6e153567dc52ea59c0498ef5383e9c7a
Name: customer_id, Length: 19979, dtype: object

In [269]:
Customers_Q2_2018=Customers_df[Customers_df["customer_id"].isin(Customers_ids)]
Customers_Q2_2018

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
14,1f1c7bf1c9b041b292af6c1c4470b753,3151a81801c8386361b62277d7fa5ecf,95110,caxias do sul,RS
17,c5c61596a3b6bd0cee5766992c48a9a1,b6e99561fe6f34a55b0b7da92f8ed775,7124,guarulhos,SP
22,2938121a40a20953c43caa8c98787fcb,482441ea6a06b1f72fe9784756c0ea75,5713,sao paulo,SP
24,cb721d7b4f271fd87011c4c83462c076,a5844ba4bfc8d0cc61d13027c7e63bcc,8225,sao paulo,SP
...,...,...,...,...,...
99431,be842c57a8c5a62e9585dd72f22b6338,ca186065de6e2d01cfc99763e6d62048,99150,marau,RS
99434,f5a0b560f9e9427792a88bec97710212,b3e53d18a997f27a3ffd16da497eaf58,7790,cajamar,SP
99436,17ddf5dd5d51696bb3d7c6291687be6f,1a29b476fee25c95fbafc67c5ac95cf8,3937,sao paulo,SP
99437,e7b71a9017aa05c9a7fd292d714858e8,d52a67c98be1cf6a5c84435bd38d095d,6764,taboao da serra,SP
99438,5e28dfe12db7fb50a4b2f691faecea5e,e9f50caf99f032f0bf3c55141f019d99,60115,fortaleza,CE

In [270]:
Orders_ids=Orders_Q2_2018["order_id"]
Orders_ids

12       82566a660a982b15fb86e904c8d32918
15       dcb36b511fcac050b97cd5c05de84dc3
26       acce194856392f074dbf9dada14d8d82
28       91b2a010e1e45e6ba3d133fa997597be
31       1790eea0b567cf50911c057cf20f90f9
                       ...
99413    3cea94817a51f34aa5937784fb4a3219
99416    c627fe35fce1a754bc5b812d0b8ff379
99422    dfc6eb45a2753ed9e6c6ef4987b44503
99427    19dba6d1e58b04e7fc820558a38ea398
99428    c22a47117b6a87c967b0c278488110c1
Name: order_id, Length: 19979, dtype: object

In [271]:
Order_items_Q2_2018=Order_Items_df[Order_Items_df["order_id"].isin(Orders_ids)]
Order_items_Q2_2018

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
16,0009c9a17f916a706d71784483a5d643,1,3f27ac8e699df3d300ec4a5d8c5cf0b2,fcb5ace8bcc92f75707dc0f01a27d269,2018-05-02 09:31:53,639.00,11.34
17,000aed2e25dbad2f9ddb70584c5a2ded,1,4fa33915031a8cde03dd0d3e8fb27f01,fe2032dab1a61af8794248c8196565c9,2018-05-16 20:57:03,144.00,8.77
28,00130c0eee84a3d909e75bc08c5c3ca1,1,89321f94e35fc6d7903d36f74e351d40,16090f2ca825584b5a147ab24aa30c86,2018-06-14 05:16:24,27.90,7.94
31,001427c0ec99cf8af737bd88e92fd444,1,28b4eced95a52d9c437a4caf9d311b95,77530e9772f57a62c906e1c21538ab82,2018-04-12 19:08:28,59.90,23.35
53,001e7cf2ad6bef3ade12ebc56ceaf0f3,1,bdcf6a834e8faa30dac3886c7a58e92e,2a84855fd20af891be03bc5924d2b453,2018-05-22 10:59:50,35.90,15.20
...,...,...,...,...,...,...,...
112609,ffea20c7630343a6cd9e09858c1295cd,1,3dd2a17168ec895c781a9191c1e95ad7,de722cd6dad950a92b7d4f82673f8833,2018-05-27 23:54:50,149.90,13.34
112624,fff0db5573c78c1cb5a2b68a2bbd8d4a,1,681953ccd5c33207d75571a4bfbe127d,777a0c55737f34ffeb78010f7542ab41,2018-07-03 09:31:23,69.95,7.75
112644,fffbee3b5462987e66fb49b1c5411df2,1,6f0169f259bb0ff432bfff7d829b9946,213b25e6f54661939f11710a6fddb871,2018-06-28 09:58:03,119.85,20.03
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79

In [272]:
Order_Payments_Q2_2018=Order_Payments_df[Order_Payments_df["order_id"].isin(Orders_ids)]
Order_Payments_Q2_2018

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45
5,298fcdf1f73eb413e4d26d01b25bc1cd,1,credit_card,2,96.12
12,616105c9352a9668c38303ad44e056cd,1,credit_card,1,75.78
...,...,...,...,...,...
103840,3fa77b110b9ab22eac07c61566e1370f,1,credit_card,1,38.96
103842,93c244c6bb63cafcde3117a2b2a5e151,1,credit_card,10,195.86
103851,df982d6b3644712f7d5070f053c8009a,1,credit_card,7,153.87
103875,60aed0a4eba0e424eb3cac85017fd752,1,credit_card,10,170.14
103879,c45067032fd84f4cf408730ff5205568,1,credit_card,2,198.94

In [273]:
Order_reviews_Q2_2018=Order_Reviews_df[Order_Reviews_df["order_id"].isin(Orders_ids)]
Order_reviews_Q2_2018

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
5,15197aa66ff4d0650b5434f1b46cda19,b18dcdf73be66366873cd26c5724d1dc,1,NaN,NaN,2018-04-13 00:00:00,2018-04-16 00:39:37
9,8670d52e15e00043ae7de4c01cc2fe06,b9bf720beb4ab3728760088589c62129,4,recomendo,aparelho eficiente. no site a marca do aparelh...,2018-05-22 00:00:00,2018-05-23 16:45:47
15,3948b09f7c818e2d86c9a546758b2335,e51478e7e277a83743b6f9991dbfa3fb,5,Super recomendo,"Vendedor confiável, produto ok e entrega antes...",2018-05-23 00:00:00,2018-05-24 03:00:01
34,c92cdd7dd544a01aa35137f901669cdf,37e7875cdce5a9e5b3a692971f370151,4,Muito bom.,Recebi exatamente o que esperava. As demais en...,2018-06-07 00:00:00,2018-06-09 18:44:02
36,08c9d79ec0eba1d252e3f52f14b8e6a9,e029f708df3cc108b3264558771605c6,5,Bom,"Recomendo ,",2018-06-13 00:00:00,2018-06-13 22:54:44
...,...,...,...,...,...,...,...
99215,a709d176f59bc3af77f4149c96bae357,d5cb12269711bd1eaf7eed8fd32a7c95,3,NaN,"O produto não foi enviado com NF, não existe v...",2018-05-19 00:00:00,2018-05-20 21:51:06
99216,115d72425fc59eec9a2e9d7594c6d93d,acd45245723df7cb52772a34416b41b1,3,NaN,NaN,2018-05-08 00:00:00,2018-05-10 14:37:03
99218,af2dc0519de6e0720ef0c74292fb4114,d699c734a0b1c8111f2272a3f36d398c,5,NaN,NaN,2018-04-27 00:00:00,2018-04-30 01:18:57
99219,574ed12dd733e5fa530cfd4bbf39d7c9,2a8c23fee101d4d5662fa670396eb8da,5,NaN,NaN,2018-07-07 00:00:00,2018-07-14 17:18:30
99222,1adeb9d84d72fe4e337617733eb85149,7725825d039fc1f0ceb7635e3f7d9206,4,NaN,NaN,2018-07-01 00:00:00,2018-07-02 12:59:13

In [274]:
os.makedirs("New_Raw_Data/Orders_Q2_2018", exist_ok=True)
Orders_Q2_2018.to_csv("New_Raw_Data/Orders_Q2_2018/Orders_Q2_2018.csv")

In [275]:
Customers_Q2_2018.to_csv("New_Raw_Data/Orders_Q2_2018/Customers_Q2_2018.csv")

In [276]:
Order_items_Q2_2018.to_csv("New_Raw_Data/Orders_Q2_2018/order_items_Q2_2018.csv")

In [277]:
Order_Payments_Q2_2018.to_csv("New_Raw_Data/Orders_Q2_2018/Order_Payments_Q2_2018.csv")

In [278]:
Order_reviews_Q2_2018.to_csv("New_Raw_Data/Orders_Q2_2018/order_reviews_Q2_2018.csv")

In [279]:
Orders_Q3_2018=Orders_df[(Orders_df["year"]==2018) & (Orders_df["quarter"]==3)]

In [280]:
Customers_ids=Orders_Q3_2018["customer_id"]
Customers_ids

1        b0830fb4747a6c6d20dea0b8c802d7ef
2        41ce2a54c0b03bf3443c3d931a367089
13       19402a48fe860416adf93348aba37740
24       62b423aab58096ca514ba6aa06be2f98
34       cf8ffeddf027932e51e4eae73b384059
                       ...
99394    e5e0698e95094be297436cbd55c2dcad
99395    aaa423fb52f4106f477683490cbd5845
99396    6f83c71b6c044fb156d697d4130fe9b5
99407    f93c9e539a9705a57902c625b611e90c
99411    eb19f77ffd29917f353d12152b0c0de1
Name: customer_id, Length: 12820, dtype: object

In [281]:
Customers_Q3_2018=Customers_df[Customers_df["customer_id"].isin(Customers_ids)]
Customers_Q3_2018

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP
16,a7c125a0a07b75146167b7f04a7f8e98,5c2991dbd08bbf3cf410713c4de5a0b5,22750,rio de janeiro,RJ
26,167bd30a409e3e4127df5a9408ebd394,9c0096673baf55453a50073f12d1a37f,74310,goiania,GO
38,4c06b42fbf7b97ab10779cda5549cd1c,07d190f123147d9e89d4b922543d7948,65075,sao luis,MA
40,4a0e66fd30684aa1409cd1b66fec77cc,86085586aaa8c5f47ed0b400da64c59d,7176,guarulhos,SP
...,...,...,...,...,...
99402,cf1ec2659f4b1f34f858a0c25e1d5d1a,592134387e7f13de6a9e38eb7d412b3d,59151,parnamirim,RN
99403,4951ae40c746cbd07eecef33fc053e89,e18e1db417f0bc97f9065c4aeae3f9d3,46500,macaubas,BA
99408,f6c6d3e1e20969a5eed982163f959719,fb354969e06f2093c0083cbfbb91864e,1521,sao paulo,SP
99409,330786b82d1da4f900da3f8124a9f4f0,ff2331f4155cedbbbca83885595b1208,6950,juquitiba,SP
99416,c156d63bdfce1d456bd43cf1c4dadfca,e5cf9da72b751849b7b217f7a943d0fa,9060,santo andre,SP

In [282]:
Orders_ids=Orders_Q3_2018["order_id"]
Orders_ids

1        53cdb2fc8bc7dce0b6741e2150273451
2        47770eb9100c2d0c44946d9cf07ec65d
13       5ff96c15d0b717ac6ad1f3d77225a350
24       f3e7c359154d965827355f39d6b1fdac
34       b276e4f8c0fb86bd82fce576f21713e0
                       ...
99394    079c9f53e6c3253320db701a645b0b9a
99395    5597332b7eded552f104108f22b023e4
99396    b3112ca67f3afd4e20cf2ee91fc4f804
99407    c2af225ac9a68a3c24500aa6fab006aa
99411    4a69678ecf74bfd34260031c04329b68
Name: order_id, Length: 12820, dtype: object

In [283]:
Order_items_Q3_2018=Order_Items_df[Order_Items_df["order_id"].isin(Orders_ids)]
Order_items_Q3_2018

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
7,000576fe39319847cbb9d288c5617fa6,1,557d850972a7d6f792fd18ae1400d9b6,5996cddab893a4652a15592fb58ab8db,2018-07-10 12:30:45,810.00,70.75
9,0005f50442cb953dcd1d21e1fb923495,1,4535b0e1091c278dfd193e5a1d63b39f,ba143b05f0110f0dc71ad71b4466ce92,2018-07-06 14:10:56,53.99,11.40
11,00063b381e2406b52ad429470734ebd5,1,f177554ea93259a5b282f24e33f65ab6,8602a61d680a10a82cceeeda0d99ea3d,2018-07-31 17:30:39,45.00,12.98
12,0006ec9db01a64e59a68b2c340bf65a7,1,99a4788cb24856965c36a24e339b6058,4a3ca9315b744ce9f8e9374361493884,2018-07-26 17:24:20,74.00,23.32
...,...,...,...,...,...,...,...
112613,ffebd80e3291e811c308365936897efd,1,4cc4d02efc8f249c13355147fb44e34d,d1c7fa84e48cfa21a0e595167c1c500e,2018-07-18 20:23:55,129.90,51.20
112619,ffee31fb4b5e35c9123608015637c495,1,b10ecf8e33aaaea419a9fa860ea80fb5,0241d4d5d36f10f80c644447315af0bd,2018-08-21 10:10:11,99.00,13.52
112628,fff3983dfa3c5a0d752d8d17baa406a0,1,092be1e8336fc404c57bd5970d056886,cbd996ad3c1b7dc71fd0e5f5df9087e2,2018-07-16 22:05:13,66.39,14.05
112633,fff8286f77788ab8b55b2e5747fa7dd8,1,a2da86fa759178e9e58e54aa1a144e59,ea8482cd71df3c1969d7b9473ff13abc,2018-07-05 22:31:13,24.99,15.28
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53

In [284]:
Order_Payments_Q3_2018=Order_Payments_df[Order_Payments_df["order_id"].isin(Orders_ids)]
Order_Payments_Q3_2018

,order_id,payment_sequential,payment_type,payment_installments,payment_value
8,1f78449c87a54faf9e96e88ba1491fa9,1,credit_card,6,341.09
16,61059985a6fc0ad64e95d9944caacdad,1,credit_card,1,132.04
23,4d680edbaa7d3d9bed69532957368a03,1,credit_card,10,353.09
27,c39414c195d0f94c9d9c35e7c6ed4f1a,1,credit_card,2,139.22
31,81cedc4d2132eb6f512354166e51b187,1,credit_card,1,30.28
...,...,...,...,...,...
103845,fbf5670723916ebf3bd62b1e33ed3ea6,1,credit_card,5,302.46
103859,e0657085c2b6297a32f39efa200cdf72,1,credit_card,1,26.37
103861,691688405bcee3ff9023639514498962,1,credit_card,1,356.53
103872,38d11c87fc409de31e930084abb0c7a4,1,credit_card,7,91.03
103884,b8b61059626efa996a60be9bb9320e10,1,credit_card,5,369.54

In [285]:
Order_reviews_Q3_2018=Order_Reviews_df[Order_Reviews_df["order_id"].isin(Orders_ids)]
Order_reviews_Q3_2018

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
7,7c6400515c67679fbee952a7525281ef,c31a859e34e3adac22f376954e19b39d,5,NaN,NaN,2018-08-14 00:00:00,2018-08-14 21:36:06
19,373cbeecea8286a2b66c97b1b157ec46,583174fbe37d3d5f0d6661be3aad1786,1,Não chegou meu produto,Péssimo,2018-08-15 00:00:00,2018-08-15 04:10:37
22,d21bbc789670eab777d27372ab9094cc,4fc44d78867142c627497b60a7e0228a,5,Ótimo,Loja nota 10,2018-07-10 00:00:00,2018-07-11 14:10:25
33,19a52a2297e5289ab4187d238d335982,677c865b89aa97e7dbeb4bfbb50bbcfd,5,NaN,NaN,2018-08-25 00:00:00,2018-08-26 22:02:59
38,b193ff3c9f32a01f3a0d9ae26b94d244,e2e6ee1ed2d7f2f36b05d234983bd7a0,5,Maravilhoso!,"Tô completamente apaixonada, loja super respon...",2018-08-10 00:00:00,2018-08-11 00:22:13
...,...,...,...,...,...,...,...
99133,a8724d975e573edc200c3e34515b8e83,b4667cd2edff64c10f3994c1395c3e3a,5,NaN,NaN,2018-08-07 00:00:00,2018-08-10 21:35:05
99162,4e1fad431debcccf54b569356ab41b50,f419e615bbdeb34741d4bdd661ff8599,5,Recomendo,"Recomendo, compra segura entrega correta.",2018-08-17 00:00:00,2018-08-18 12:07:22
99168,504d1c6f33263b45fb171e39d9f0dc1f,64a22766d8a3975ba61edc4943501e24,5,NaN,NaN,2018-07-11 00:00:00,2018-07-12 12:03:57
99199,40743b46a0ee86375cedb95e82b78d75,3e93213bb8fdda91186b4018b2fe0030,5,OTIMA EMBALAGEM,NaN,2018-08-08 00:00:00,2018-08-08 16:56:16
99207,586e77c5f02b95285a939083359f8241,5f4a120717a4d152577d7d2ec66c45be,5,NaN,NaN,2018-08-05 00:00:00,2018-08-06 09:48:41

In [286]:
os.makedirs("New_Raw_Data/Orders_Q3_2018", exist_ok=True)
Orders_Q3_2018.to_csv("New_Raw_Data/Orders_Q3_2018/Orders_Q3_2018.csv")

In [287]:
Customers_Q3_2018.to_csv("New_Raw_Data/Orders_Q3_2018/Customers_Q3_2018.csv")

In [288]:
Order_items_Q3_2018.to_csv("New_Raw_Data/Orders_Q3_2018/order_items_Q3_2018.csv")

In [289]:
Order_Payments_Q3_2018.to_csv("New_Raw_Data/Orders_Q3_2018/Order_Payments_Q3_2018.csv")

In [290]:
Order_reviews_Q3_2018.to_csv("New_Raw_Data/Orders_Q3_2018/order_reviews_Q3_2018.csv")

In [291]:
Orders_Q4_2018=Orders_df[(Orders_df["year"]==2018) & (Orders_df["quarter"]==4)]

In [292]:
Customers_ids=Orders_Q4_2018["customer_id"]
Customers_ids

31891    4c2ec60c29d10c34bd49cb88aa85cfc4
60938    a4b417188addbc05b26b72d5e44837a1
68373    856336203359aa6a61bf3826f7d84c49
88500    bf6181a85bbb4115736c0a8db1a53be3
Name: customer_id, dtype: object

In [293]:
Customers_Q4_2018=Customers_df[Customers_df["customer_id"].isin(Customers_ids)]
Customers_Q4_2018

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
68312,4c2ec60c29d10c34bd49cb88aa85cfc4,af5454198a97379394cacf676e1e96cb,11900,registro,SP
69139,856336203359aa6a61bf3826f7d84c49,262e1f1e26e92e86375f86840b4ffd63,64600,picos,PI
75902,bf6181a85bbb4115736c0a8db1a53be3,634420a0ea42302205032ed44ac7fccc,27175,pirai,RJ
85415,a4b417188addbc05b26b72d5e44837a1,87ab9fec999db8bd5774917de3cdf01c,18077,sorocaba,SP

In [294]:
Orders_ids=Orders_Q4_2018["order_id"]
Orders_ids

31891    a2ac6dad85cf8af5b0afb510a240fe8c
60938    10a045cdf6a5650c21e9cfeb60384c16
68373    b059ee4de278302d550a3035c4cdb740
88500    616fa7d4871b87832197b2a137a115d2
Name: order_id, dtype: object

In [295]:
Order_Payments_Q4_2018=Order_Payments_df[Order_Payments_df["order_id"].isin(Orders_ids)]
Order_Payments_Q4_2018

,order_id,payment_sequential,payment_type,payment_installments,payment_value
5106,b059ee4de278302d550a3035c4cdb740,1,voucher,1,222.03
10552,10a045cdf6a5650c21e9cfeb60384c16,1,voucher,1,89.71
35636,616fa7d4871b87832197b2a137a115d2,1,voucher,1,80.38
64016,a2ac6dad85cf8af5b0afb510a240fe8c,1,voucher,1,197.55

In [296]:
Order_reviews_Q4_2018=Order_Reviews_df[Order_Reviews_df["order_id"].isin(Orders_ids)]
Order_reviews_Q4_2018

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
37168,8b8f495d30fca09fdc8312e96de1bc47,616fa7d4871b87832197b2a137a115d2,2,NaN,NaN,2018-08-23 00:00:00,2018-08-23 23:14:33
59696,716eff9ef436f351494c303085fcfcf5,10a045cdf6a5650c21e9cfeb60384c16,1,Troca,"Por gentileza, trocar meu produto pois comprei...",2018-08-23 00:00:00,2018-08-24 02:56:26
92235,48198628b2d43ed394089750acc59c3f,b059ee4de278302d550a3035c4cdb740,5,Gostei,Os produtos são de boa qualidade e o preço que...,2018-06-27 00:00:00,2018-06-30 01:48:53
92768,4548534449b1f572e357211b90724f1b,a2ac6dad85cf8af5b0afb510a240fe8c,1,NaN,quero devolver o produto comprei um veio outro...,2018-08-18 00:00:00,2018-08-19 00:39:54

In [297]:
os.makedirs("New_Raw_Data/Orders_Q4_2018", exist_ok=True)
Orders_Q4_2018.to_csv("New_Raw_Data/Orders_Q4_2018/Orders_Q4_2018.csv")

In [298]:
Customers_Q4_2018.to_csv("New_Raw_Data/Orders_Q4_2018/Customers_Q4_2018.csv")

In [299]:
Order_Payments_Q4_2018.to_csv("New_Raw_Data/Orders_Q4_2018/Order_Payments_Q4_2018.csv")

In [300]:
Order_reviews_Q4_2018.to_csv("New_Raw_Data/Orders_Q4_2018/order_reviews_Q4_2018.csv")

## Now after i completed the incremental part i will deal with the tables that will upload in the inital load

In [301]:
Products_df

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0
...,...,...,...,...,...,...,...,...,...
32946,a0b7d5a992ccda646f2d34e418fff5a0,moveis_decoracao,45.0,67.0,2.0,12300.0,40.0,40.0,40.0
32947,bf4538d88321d0fd4412a93c974510e6,construcao_ferramentas_iluminacao,41.0,971.0,1.0,1700.0,16.0,19.0,16.0
32948,9a7c6041fa9592d9d9ef6cfe62a71f8c,cama_mesa_banho,50.0,799.0,1.0,1400.0,27.0,7.0,27.0
32949,83808703fc0706a22e264b9d75f04a2e,informatica_acessorios,60.0,156.0,2.0,700.0,31.0,13.0,20.0
32950,106392145fca363410d287a815be6de4,cama_mesa_banho,58.0,309.0,1.0,2083.0,12.0,2.0,7.0

In [302]:
products_df=pd.merge(Products_df,Translation_df,on="product_category_name",how="left")
products_df

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_category_name_english
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0,perfumery
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0,art
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0,sports_leisure
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0,baby
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0,housewares
...,...,...,...,...,...,...,...,...,...,...
32946,a0b7d5a992ccda646f2d34e418fff5a0,moveis_decoracao,45.0,67.0,2.0,12300.0,40.0,40.0,40.0,furniture_decor
32947,bf4538d88321d0fd4412a93c974510e6,construcao_ferramentas_iluminacao,41.0,971.0,1.0,1700.0,16.0,19.0,16.0,construction_tools_lights
32948,9a7c6041fa9592d9d9ef6cfe62a71f8c,cama_mesa_banho,50.0,799.0,1.0,1400.0,27.0,7.0,27.0,bed_bath_table
32949,83808703fc0706a22e264b9d75f04a2e,informatica_acessorios,60.0,156.0,2.0,700.0,31.0,13.0,20.0,computers_accessories
32950,106392145fca363410d287a815be6de4,cama_mesa_banho,58.0,309.0,1.0,2083.0,12.0,2.0,7.0,bed_bath_table

## The Same zip_code can have multiple lat and lon

In [303]:
geolocation_df

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP
...,...,...,...,...,...
1000158,99950,-28.068639,-52.010705,tapejara,RS
1000159,99900,-27.877125,-52.224882,getulio vargas,RS
1000160,99950,-28.071855,-52.014716,tapejara,RS
1000161,99980,-28.388932,-51.846871,david canabarro,RS
1000162,99950,-28.070104,-52.018658,tapejara,RS

In [304]:
geolocation_df["geolocation_zip_code_prefix"].value_counts()

geolocation_zip_code_prefix
24220    1146
24230    1102
38400     965
35500     907
11680     879
         ...
75843       1
75814       1
46410       1
45104       1
2088        1
Name: count, Length: 19015, dtype: int64

In [305]:
geolocation_dedup = geolocation_df.groupby("geolocation_zip_code_prefix").agg({
    "geolocation_lat" :"mean",
    "geolocation_lng" : "mean"}).reset_index()

In [306]:
geolocation_dedup

       geolocation_zip_code_prefix  geolocation_lat  geolocation_lng
0                             1001       -23.550190       -46.634024
1                             1002       -23.548146       -46.634979
2                             1003       -23.548994       -46.635731
3                             1004       -23.549799       -46.634757
4                             1005       -23.549456       -46.636733
...                            ...              ...              ...
19010                        99960       -27.953722       -52.025511
19011                        99965       -28.183372       -52.039850
19012                        99970       -28.343766       -51.874689
19013                        99980       -28.389129       -51.843836
19014                        99990       -28.329595       -51.769362

[19015 rows x 3 columns]

In [307]:
Sellers_df

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP
...,...,...,...,...
3090,98dddbc4601dd4443ca174359b237166,87111,sarandi,PR
3091,f8201cab383e484733266d1906e2fdfa,88137,palhoca,SC
3092,74871d19219c7d518d0090283e03c137,4650,sao paulo,SP
3093,e603cf3fec55f8697c9059638d6c8eb5,96080,pelotas,RS
3094,9e25199f6ef7e7c347120ff175652c3b,12051,taubate,SP

In [308]:
Sellers_df=pd.merge(Sellers_df,geolocation_dedup,left_on="seller_zip_code_prefix",right_on="geolocation_zip_code_prefix",how="left")

In [309]:
Sellers_df

,seller_id,seller_zip_code_prefix,seller_city,seller_state,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP,13023.0,-22.893848,-47.061337
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP,13844.0,-22.383437,-46.947927
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ,20031.0,-22.909572,-43.177703
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP,4195.0,-23.657242,-46.612831
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP,12914.0,-22.964803,-46.534419
...,...,...,...,...,...,...,...
3090,98dddbc4601dd4443ca174359b237166,87111,sarandi,PR,87111.0,-23.448041,-51.869960
3091,f8201cab383e484733266d1906e2fdfa,88137,palhoca,SC,88137.0,-27.656421,-48.665840
3092,74871d19219c7d518d0090283e03c137,4650,sao paulo,SP,4650.0,-23.657851,-46.676925
3093,e603cf3fec55f8697c9059638d6c8eb5,96080,pelotas,RS,96080.0,-31.751072,-52.323202
3094,9e25199f6ef7e7c347120ff175652c3b,12051,taubate,SP,12051.0,-23.012009,-45.585652

In [310]:
Sellers_df.drop(columns=["geolocation_zip_code_prefix"],inplace=True)

In [311]:
Sellers_df

,seller_id,seller_zip_code_prefix,seller_city,seller_state,geolocation_lat,geolocation_lng
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP,-22.893848,-47.061337
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP,-22.383437,-46.947927
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ,-22.909572,-43.177703
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP,-23.657242,-46.612831
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP,-22.964803,-46.534419
...,...,...,...,...,...,...
3090,98dddbc4601dd4443ca174359b237166,87111,sarandi,PR,-23.448041,-51.869960
3091,f8201cab383e484733266d1906e2fdfa,88137,palhoca,SC,-27.656421,-48.665840
3092,74871d19219c7d518d0090283e03c137,4650,sao paulo,SP,-23.657851,-46.676925
3093,e603cf3fec55f8697c9059638d6c8eb5,96080,pelotas,RS,-31.751072,-52.323202
3094,9e25199f6ef7e7c347120ff175652c3b,12051,taubate,SP,-23.012009,-45.585652

## Make connection to sql server

In [316]:
import pyodbc
from dotenv import load_dotenv
import os

In [317]:
load_dotenv()

server = os.getenv("DB_SERVER")
database = os.getenv("DB_DATABASE")
username = os.getenv("DB_USERNAME")
password = os.getenv("DB_PASSWORD")
driver = os.getenv("DB_DRIVER")

In [318]:
conn_str = (
    f"DRIVER={{{driver}}};"
    f"SERVER={server};"
    f"DATABASE={database};"
    f"UID={username};"
    f"PWD={password};"
    f"TrustServerCertificate=yes;"
)

In [319]:
conn = pyodbc.connect(conn_str)
cursor = conn.cursor()

## Table Customers in sql server

In [320]:
Customers_df

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP
...,...,...,...,...,...
99436,17ddf5dd5d51696bb3d7c6291687be6f,1a29b476fee25c95fbafc67c5ac95cf8,3937,sao paulo,SP
99437,e7b71a9017aa05c9a7fd292d714858e8,d52a67c98be1cf6a5c84435bd38d095d,6764,taboao da serra,SP
99438,5e28dfe12db7fb50a4b2f691faecea5e,e9f50caf99f032f0bf3c55141f019d99,60115,fortaleza,CE
99439,56b18e2166679b8a959d72dd06da27f9,73c2643a0a458b49f58cea58833b192e,92120,canoas,RS
99440,274fa6071e5e17fe303b9748641082c8,84732c5050c01db9b23e19ba39899398,6703,cotia,SP

In [321]:
Customers_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

In [322]:
Customers_df["customer_state"].str.len().max()

np.int64(2)

In [323]:
cursor.execute("""
Create Table Customers (
customer_id varchar(50) not null primary key,
customer_unique_id varchar(50) not null,
customer_zip_code_prefix int,
customer_city varchar(100),
customer_state varchar(5),
created_at datetime default getdate(),
last_modified_at datetime default getdate()) """)
conn.commit()

## Table Sellers in sql server

In [324]:
Sellers_df

,seller_id,seller_zip_code_prefix,seller_city,seller_state,geolocation_lat,geolocation_lng
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP,-22.893848,-47.061337
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP,-22.383437,-46.947927
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ,-22.909572,-43.177703
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP,-23.657242,-46.612831
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP,-22.964803,-46.534419
...,...,...,...,...,...,...
3090,98dddbc4601dd4443ca174359b237166,87111,sarandi,PR,-23.448041,-51.869960
3091,f8201cab383e484733266d1906e2fdfa,88137,palhoca,SC,-27.656421,-48.665840
3092,74871d19219c7d518d0090283e03c137,4650,sao paulo,SP,-23.657851,-46.676925
3093,e603cf3fec55f8697c9059638d6c8eb5,96080,pelotas,RS,-31.751072,-52.323202
3094,9e25199f6ef7e7c347120ff175652c3b,12051,taubate,SP,-23.012009,-45.585652

In [325]:
Sellers_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   object
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   object
 3   seller_state            3095 non-null   object
 4   geolocation_lat         3088 non-null   float64
 5   geolocation_lng         3088 non-null   float64
dtypes: float64(2), int64(1), object(3)
memory usage: 145.2+ KB

In [326]:
Sellers_df["seller_id"].str.len().max()

np.int64(32)

In [327]:
cursor.execute("""
Create Table Sellers (
Seller_id varchar(50) not null primary key,
seller_zip_code_prefix int,
seller_city varchar(100),
seller_state varchar(5),
geolocation_lat float,
geolocation_lng float
) """)
conn.commit()

## Table Products in sql server

In [328]:
products_df

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_category_name_english
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0,perfumery
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0,art
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0,sports_leisure
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0,baby
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0,housewares
...,...,...,...,...,...,...,...,...,...,...
32946,a0b7d5a992ccda646f2d34e418fff5a0,moveis_decoracao,45.0,67.0,2.0,12300.0,40.0,40.0,40.0,furniture_decor
32947,bf4538d88321d0fd4412a93c974510e6,construcao_ferramentas_iluminacao,41.0,971.0,1.0,1700.0,16.0,19.0,16.0,construction_tools_lights
32948,9a7c6041fa9592d9d9ef6cfe62a71f8c,cama_mesa_banho,50.0,799.0,1.0,1400.0,27.0,7.0,27.0,bed_bath_table
32949,83808703fc0706a22e264b9d75f04a2e,informatica_acessorios,60.0,156.0,2.0,700.0,31.0,13.0,20.0,computers_accessories
32950,106392145fca363410d287a815be6de4,cama_mesa_banho,58.0,309.0,1.0,2083.0,12.0,2.0,7.0,bed_bath_table

In [329]:
products_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 10 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_id                     32951 non-null  object
 1   product_category_name          32341 non-null  object
 2   product_name_lenght            32341 non-null  float64
 3   product_description_lenght     32341 non-null  float64
 4   product_photos_qty             32341 non-null  float64
 5   product_weight_g               32949 non-null  float64
 6   product_length_cm              32949 non-null  float64
 7   product_height_cm              32949 non-null  float64
 8   product_width_cm               32949 non-null  float64
 9   product_category_name_english  32328 non-null  object
dtypes: float64(7), object(3)
memory usage: 2.5+ MB

In [330]:
products_df["product_category_name_english"].str.len().max()

np.float64(39.0)

In [331]:
cursor.execute("""
Create Table Products (
Product_id varchar(50) not null primary key,
product_category_name varchar(100),
product_name_lenght float,
product_description_lenght float,
product_photos_qty float,
product_weight_g float,
product_length_cm float,
product_height_cm float,
product_width_cm float,
product_category_name_english varchar(50)
) """)
conn.commit()

## Table Orders in sql server

In [332]:
Orders_df

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,year,quarter
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,2017,4
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,2018,3
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,2018,3
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00,2017,4
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00,2018,1
...,...,...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28 00:00:00,2017,1
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00,2018,1
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00,2017,3
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00,2018,1
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00,2018,1

In [333]:
Orders_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 10 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  datetime64[ns]
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
 8   year                           99441 non-null  int32
 9   quarter                        99441 non-null  int32
dtypes: datetime64[ns](1), int32(2), object(7)
memory usage: 6.8+ MB

In [334]:
Orders_df["order_status"].str.len().max()

np.int64(11)

In [335]:
cursor.execute("""
Create Table Orders (
order_id varchar(50) not null primary key,
customer_id varchar(50) not null,
order_status varchar(20),
order_purchase_timestamp datetime,
order_approved_at datetime,
order_delivered_carrier_date datetime,
order_delivered_customer_date datetime,
order_estimated_delivery_date datetime,
year int,
quarter int,
created_at datetime default getdate(),
last_modified_at datetime default getdate(),
CONSTRAINT FK_orders_customers FOREIGN KEY (customer_id) REFERENCES Customers(customer_id)
) """)
conn.commit()

## Table Order_items in sql server

In [336]:
Order_items_Q3_2016

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
20265,2e7a8482f6fb09756ca50c10d7bfc047,1,c1488892604e4ba5cff5b4eb4d595400,1554a68530182680ad5c8b042c3ab563,2016-10-26 18:25:19,39.99,31.67
20266,2e7a8482f6fb09756ca50c10d7bfc047,2,f293394c72c9b5fafd7023301fc21fc2,1554a68530182680ad5c8b042c3ab563,2016-10-26 18:25:19,32.90,31.67
84389,bfbd0f9bdef84302105ad712db648a6c,1,5a6b04657a4c5ee34285d1e4619a96b4,ecccfa2bb93b34a3bf033cc5d1dcdc69,2016-09-19 23:11:33,44.99,2.83
84390,bfbd0f9bdef84302105ad712db648a6c,2,5a6b04657a4c5ee34285d1e4619a96b4,ecccfa2bb93b34a3bf033cc5d1dcdc69,2016-09-19 23:11:33,44.99,2.83
84391,bfbd0f9bdef84302105ad712db648a6c,3,5a6b04657a4c5ee34285d1e4619a96b4,ecccfa2bb93b34a3bf033cc5d1dcdc69,2016-09-19 23:11:33,44.99,2.83
101394,e5fa5a7210941f7d56d0208e4e071d35,1,f3c2d01a84c947b078e32bbef0718962,a425f92c199eb576938df686728acd20,2016-09-19 00:15:34,59.50,15.56

In [337]:
Order_items_Q3_2016.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, 20265 to 101394
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   order_id             6 non-null      object
 1   order_item_id        6 non-null      int64
 2   product_id           6 non-null      object
 3   seller_id            6 non-null      object
 4   shipping_limit_date  6 non-null      object
 5   price                6 non-null      float64
 6   freight_value        6 non-null      float64
dtypes: float64(2), int64(1), object(4)
memory usage: 384.0+ bytes

In [338]:
Order_items_Q3_2016["order_id"].str.len().max()

np.int64(32)

In [339]:
cursor.execute("""
Create Table Order_Items (
order_id varchar(50) not null ,
order_item_id int not null,
product_id varchar(50) not null,
seller_id varchar(50) not null,
shipping_limit_date datetime,
price float,
freight_value float,
created_at datetime default getdate(),
last_modified_at datetime default getdate(),
CONSTRAINT PK_order_items PRIMARY KEY (order_id, order_item_id),
CONSTRAINT FK_items_orders FOREIGN KEY (order_id) REFERENCES Orders(order_id),
CONSTRAINT FK_items_products FOREIGN KEY (product_id) REFERENCES Products(product_id),
CONSTRAINT FK_items_sellers FOREIGN KEY (seller_id) REFERENCES Sellers(seller_id)
) """)
conn.commit()

## Table Order_Payments in sql server

In [340]:
Order_Payments_Q3_2016

,order_id,payment_sequential,payment_type,payment_installments,payment_value
27216,2e7a8482f6fb09756ca50c10d7bfc047,1,credit_card,1,136.23
58826,809a282bbd5dbcabb6f2f724fca862ec,1,credit_card,2,40.95
61536,e5fa5a7210941f7d56d0208e4e071d35,1,credit_card,3,75.06

In [341]:
Order_Payments_Q3_2016.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, 27216 to 61536
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   order_id              3 non-null      object
 1   payment_sequential    3 non-null      int64
 2   payment_type          3 non-null      object
 3   payment_installments  3 non-null      int64
 4   payment_value         3 non-null      float64
dtypes: float64(1), int64(2), object(2)
memory usage: 144.0+ bytes

In [342]:
Order_Payments_Q3_2016["payment_type"].str.len().max()

np.int64(11)

In [343]:
cursor.execute("""
Create Table Order_Payments (
order_id varchar(50) not null ,
payment_sequential int not null,
payment_type varchar(20) ,
payment_installments int,
payment_value float,
created_at datetime default getdate(),
last_modified_at datetime default getdate(),
CONSTRAINT PK_order_payments PRIMARY KEY (order_id, payment_sequential),
CONSTRAINT FK_payments_orders FOREIGN KEY (order_id) REFERENCES Orders(order_id)
) """)
conn.commit()

## Table Order_Reviews in sql server

In [344]:
Order_reviews_Q3_2016

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
30479,a93139d9d1314158c080e3db7e79618b,e5fa5a7210941f7d56d0208e4e071d35,1,NaN,Comprei dois produtos desta loja parceira da l...,2016-10-29 00:00:00,2016-10-30 01:47:48
37547,6916ca4502d6d3bfd39818759d55d536,bfbd0f9bdef84302105ad712db648a6c,1,NaN,nao recebi o produto e nem resposta da empresa,2016-10-06 00:00:00,2016-10-07 18:32:28
70906,69ac6a27fde9855ebeaaecac0f78058b,809a282bbd5dbcabb6f2f724fca862ec,1,NaN,MEU PEDIDO NÃO FOI ENTREGUE E NÃO FOI DADA NEN...,2016-10-02 00:00:00,2016-10-26 12:31:00
74443,cef1ee03ded4d6272894a2eead6e1328,2e7a8482f6fb09756ca50c10d7bfc047,1,NaN,1 mes de atraso na entrega !!! ultima compra q...,2016-10-22 00:00:00,2016-11-15 16:00:34

In [345]:
Order_reviews_Q3_2016.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, 30479 to 74443
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                4 non-null      object
 1   order_id                 4 non-null      object
 2   review_score             4 non-null      int64
 3   review_comment_title     0 non-null      object
 4   review_comment_message   4 non-null      object
 5   review_creation_date     4 non-null      object
 6   review_answer_timestamp  4 non-null      object
dtypes: int64(1), object(6)
memory usage: 256.0+ bytes

In [346]:
Order_reviews_Q3_2016["review_comment_message"].str.len().max()

np.int64(125)

In [347]:
cursor.execute("""
Create Table Order_Reviews (
review_id varchar(50) not null,
order_id varchar(50) not null ,
review_score int,
review_comment_title varchar(200) ,
review_comment_message varchar(max),
review_creation_date datetime,
review_answer_timestamp datetime,
created_at datetime default getdate(),
last_modified_at datetime default getdate(),
CONSTRAINT PK_order_reviews PRIMARY KEY (review_id, order_id),
CONSTRAINT FK_reviews_orders FOREIGN KEY (order_id) REFERENCES Orders(order_id)
) """)
conn.commit()

## I will load data to sql server tables

In [348]:
from sqlalchemy import create_engine
import urllib

In [349]:
params = urllib.parse.quote_plus(
    f"DRIVER={{{driver}}};"
    f"SERVER={server};"
    f"DATABASE={database};"
    f"UID={username};"
    f"PWD={password};"
    f"TrustServerCertificate=yes;"
)
engine = create_engine(f"mssql+pyodbc:///?odbc_connect={params}")

In [350]:
Sellers_df.to_sql("Sellers",con=engine,if_exists="append",index=False)

303

In [351]:
products_df.to_sql("Products",con=engine,if_exists="append",index=False)

138

In [352]:
Customers_Q3_2016.to_sql("Customers",con=engine,if_exists="append",index=False)

4

In [353]:
Orders_Q3_2016.to_sql("Orders",con=engine,if_exists="append",index=False)

4

In [354]:
Order_items_Q3_2016.to_sql("Order_Items",con=engine,if_exists="append",index=False)

6

In [355]:
Order_reviews_Q3_2016.to_sql("Order_Reviews",con=engine,if_exists="append",index=False)

4

In [356]:
Order_Payments_Q3_2016.to_sql("Order_Payments",con=engine,if_exists="append",index=False)

3

## Table Geolocation in sql server

In [357]:
geolocation_dedup

       geolocation_zip_code_prefix  geolocation_lat  geolocation_lng
0                             1001       -23.550190       -46.634024
1                             1002       -23.548146       -46.634979
2                             1003       -23.548994       -46.635731
3                             1004       -23.549799       -46.634757
4                             1005       -23.549456       -46.636733
...                            ...              ...              ...
19010                        99960       -27.953722       -52.025511
19011                        99965       -28.183372       -52.039850
19012                        99970       -28.343766       -51.874689
19013                        99980       -28.389129       -51.843836
19014                        99990       -28.329595       -51.769362

[19015 rows x 3 columns]

In [358]:
geolocation_dedup.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19015 entries, 0 to 19014
Data columns (total 3 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   geolocation_zip_code_prefix  19015 non-null  int64
 1   geolocation_lat              19015 non-null  float64
 2   geolocation_lng              19015 non-null  float64
dtypes: float64(2), int64(1)
memory usage: 445.8 KB

In [359]:
cursor.execute("""
Create Table Geolocation (
geolocation_zip_code_prefix int not null primary key,
geolocation_lat float ,
geolocation_lng float
) """)
conn.commit()

In [360]:
geolocation_dedup.to_sql("Geolocation",con=engine,if_exists="append",index=False)

142

## Now i Will make triggers to update last_modified_at when something changes in a row

In [361]:
## Customers
cursor.execute("""
CREATE trigger tr_customers_modified
ON Customers
AFTER UPDATE
AS
BEGIN
    UPDATE C
    SET last_modified_at = GETDATE()
    FROM Customers C
    INNER JOIN inserted i ON C.customer_id = i.customer_id;
END;
 """)
conn.commit()

In [362]:
## Orders
cursor.execute("""
CREATE trigger tr_orders_modified
ON Orders
AFTER UPDATE
AS
BEGIN
    UPDATE o
    SET last_modified_at = GETDATE()
    FROM Orders o
    INNER JOIN inserted i ON o.order_id = i.order_id;
END;
 """)
conn.commit()

In [363]:
## Order_Items
cursor.execute("""
CREATE trigger tr_order_items_modified
ON Order_Items
AFTER UPDATE
AS
BEGIN
    UPDATE oi
    SET last_modified_at = GETDATE()
    FROM Order_Items oi
    INNER JOIN inserted i ON oi.order_id = i.order_id and oi.order_item_id = i.order_item_id;
END;
 """)
conn.commit()

In [364]:
## Order_Payments
cursor.execute("""
CREATE trigger tr_order_payments_modified
ON Order_Payments
AFTER UPDATE
AS
BEGIN
    UPDATE op
    SET last_modified_at = GETDATE()
    FROM Order_Payments op
    INNER JOIN inserted i ON op.order_id = i.order_id and op.payment_sequential = i.payment_sequential;
END;
 """)
conn.commit()

In [365]:
## Order_Reviews
cursor.execute("""
CREATE trigger tr_order_reviews_modified
ON Order_Reviews
AFTER UPDATE
AS
BEGIN
    UPDATE r
    SET last_modified_at = GETDATE()
    FROM Order_Reviews r
    INNER JOIN inserted i ON r.review_id = i.review_id ;
END;
 """)
conn.commit()

## Now I will make the first incremental load

In [366]:
Customers_Q4_2016.to_sql("Customers",con=engine,if_exists="append",index=False)

325

In [367]:
Orders_Q4_2016.to_sql("Orders",con=engine,if_exists="append",index=False)

116

In [368]:
Order_items_Q4_2016.to_sql("Order_Items",con=engine,if_exists="append",index=False)

65

In [369]:
Order_reviews_Q4_2016.to_sql("Order_Reviews",con=engine,if_exists="append",index=False)

23

In [370]:
Order_Payments_Q4_2016.to_sql("Order_Payments",con=engine,if_exists="append",index=False)

343

## Second incremental load

In [372]:
Customers_Q1_2017.to_sql("Customers",con=engine,if_exists="append",index=False)

234

In [373]:
Orders_Q1_2017.to_sql("Orders",con=engine,if_exists="append",index=False)

37

In [374]:
Order_items_Q1_2017.to_sql("Order_Items",con=engine,if_exists="append",index=False)

225

In [375]:
Order_reviews_Q1_2017.to_sql("Order_Reviews",con=engine,if_exists="append",index=False)

166

In [376]:
Order_Payments_Q1_2017.to_sql("Order_Payments",con=engine,if_exists="append",index=False)

126

## Third incremental load

In [377]:
Customers_Q2_2017.to_sql("Customers",con=engine,if_exists="append",index=False)

131

In [378]:
Orders_Q2_2017.to_sql("Orders",con=engine,if_exists="append",index=False)

153

In [379]:
Order_items_Q2_2017.to_sql("Order_Items",con=engine,if_exists="append",index=False)

237

In [380]:
Order_reviews_Q2_2017.to_sql("Order_Reviews",con=engine,if_exists="append",index=False)

78

In [381]:
Order_Payments_Q2_2017.to_sql("Order_Payments",con=engine,if_exists="append",index=False)

314

## Q3 - 2017

In [382]:
Customers_Q3_2017.to_sql("Customers",con=engine,if_exists="append",index=False)

72

In [383]:
Orders_Q3_2017.to_sql("Orders",con=engine,if_exists="append",index=False)

102

In [384]:
Order_items_Q3_2017.to_sql("Order_Items",con=engine,if_exists="append",index=False)

207

In [385]:
Order_reviews_Q3_2017.to_sql("Order_Reviews",con=engine,if_exists="append",index=False)

92

In [386]:
Order_Payments_Q3_2017.to_sql("Order_Payments",con=engine,if_exists="append",index=False)

394

## Q4 - 2017

In [ ]:
Customers_Q4_2017.to_sql("Customers",con=engine,if_exists="append",index=False)

In [389]:
Orders_Q4_2017.to_sql("Orders",con=engine,if_exists="append",index=False)

83

In [391]:
Order_items_Q4_2017.to_sql("Order_Items",con=engine,if_exists="append",index=False)

262

In [392]:
Order_reviews_Q4_2017.to_sql("Order_Reviews",con=engine,if_exists="append",index=False)

157

In [393]:
Order_Payments_Q4_2017.to_sql("Order_Payments",con=engine,if_exists="append",index=False)

The history saving thread hit an unexpected error (OperationalError('database or disk is full')).History will not be written to the database.

182

## Q1 - 2018

In [394]:
Customers_Q1_2018.to_sql("Customers",con=engine,if_exists="append",index=False)

258

In [395]:
Orders_Q1_2018.to_sql("Orders",con=engine,if_exists="append",index=False)

99

In [396]:
Order_items_Q1_2018.to_sql("Order_Items",con=engine,if_exists="append",index=False)

177

In [397]:
Order_reviews_Q1_2018.to_sql("Order_Reviews",con=engine,if_exists="append",index=False)

260

In [398]:
Order_Payments_Q1_2018.to_sql("Order_Payments",con=engine,if_exists="append",index=False)

239

## Q2- 2018

In [399]:
Customers_Q2_2018.to_sql("Customers",con=engine,if_exists="append",index=False)

286

In [400]:
Orders_Q2_2018.to_sql("Orders",con=engine,if_exists="append",index=False)

124

In [401]:
Order_items_Q2_2018.to_sql("Order_Items",con=engine,if_exists="append",index=False)

254

In [402]:
Order_reviews_Q2_2018.to_sql("Order_Reviews",con=engine,if_exists="append",index=False)

155

In [403]:
Order_Payments_Q2_2018.to_sql("Order_Payments",con=engine,if_exists="append",index=False)

232

## Q3 - 2018

In [404]:
Customers_Q3_2018.to_sql("Customers",con=engine,if_exists="append",index=False)

250

In [405]:
Orders_Q3_2018.to_sql("Orders",con=engine,if_exists="append",index=False)

71

In [406]:
Order_items_Q3_2018.to_sql("Order_Items",con=engine,if_exists="append",index=False)

288

In [407]:
Order_reviews_Q3_2018.to_sql("Order_Reviews",con=engine,if_exists="append",index=False)

213

In [408]:
Order_Payments_Q3_2018.to_sql("Order_Payments",con=engine,if_exists="append",index=False)

232

## Q4 - 2018

In [409]:
Customers_Q4_2018.to_sql("Customers",con=engine,if_exists="append",index=False)

4

In [410]:
Orders_Q4_2018.to_sql("Orders",con=engine,if_exists="append",index=False)

4

In [412]:
Order_reviews_Q4_2018.to_sql("Order_Reviews",con=engine,if_exists="append",index=False)

4

In [413]:
Order_Payments_Q4_2018.to_sql("Order_Payments",con=engine,if_exists="append",index=False)

4